// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SingleTrackResult.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__CASIA_DEVICE_DETECTION_SINGLETRACKRESULT_HPP
#define FAST_DDS_GENERATED__CASIA_DEVICE_DETECTION_SINGLETRACKRESULT_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SINGLETRACKRESULT_SOURCE)
#define SINGLETRACKRESULT_DllAPI __declspec( dllexport )
#else
#define SINGLETRACKRESULT_DllAPI __declspec( dllimport )
#endif // SINGLETRACKRESULT_SOURCE
#else
#define SINGLETRACKRESULT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SINGLETRACKRESULT_DllAPI
#endif // _WIN32

namespace casia {

namespace device {

namespace detection {

/*!
 * @brief This class represents the structure BoundingBox defined by the user in the IDL file.
 * @ingroup SingleTrackResult
 */
class BoundingBox
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport BoundingBox()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~BoundingBox()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object BoundingBox that will be copied.
     */
    eProsima_user_DllExport BoundingBox(
            const BoundingBox& x)
    {
                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_width = x.m_width;

                    m_height = x.m_height;

                    m_boxId = x.m_boxId;

                    m_classId = x.m_classId;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object BoundingBox that will be copied.
     */
    eProsima_user_DllExport BoundingBox(
            BoundingBox&& x) noexcept
    {
        m_x = x.m_x;
        m_y = x.m_y;
        m_width = x.m_width;
        m_height = x.m_height;
        m_boxId = x.m_boxId;
        m_classId = x.m_classId;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object BoundingBox that will be copied.
     */
    eProsima_user_DllExport BoundingBox& operator =(
            const BoundingBox& x)
    {

                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_width = x.m_width;

                    m_height = x.m_height;

                    m_boxId = x.m_boxId;

                    m_classId = x.m_classId;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object BoundingBox that will be copied.
     */
    eProsima_user_DllExport BoundingBox& operator =(
            BoundingBox&& x) noexcept
    {

        m_x = x.m_x;
        m_y = x.m_y;
        m_width = x.m_width;
        m_height = x.m_height;
        m_boxId = x.m_boxId;
        m_classId = x.m_classId;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x BoundingBox object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const BoundingBox& x) const
    {
        return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_width == x.m_width &&
           m_height == x.m_height &&
           m_boxId == x.m_boxId &&
           m_classId == x.m_classId);
    }

    /*!
     * @brief Comparison operator.
     * @param x BoundingBox object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const BoundingBox& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(
            int16_t _x)
    {
        m_x = _x;
    }

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport int16_t x() const
    {
        return m_x;
    }

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport int16_t& x()
    {
        return m_x;
    }


    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    eProsima_user_DllExport void y(
            int16_t _y)
    {
        m_y = _y;
    }

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    eProsima_user_DllExport int16_t y() const
    {
        return m_y;
    }

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport int16_t& y()
    {
        return m_y;
    }


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            int16_t _width)
    {
        m_width = _width;
    }

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport int16_t width() const
    {
        return m_width;
    }

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport int16_t& width()
    {
        return m_width;
    }


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            int16_t _height)
    {
        m_height = _height;
    }

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport int16_t height() const
    {
        return m_height;
    }

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport int16_t& height()
    {
        return m_height;
    }


    /*!
     * @brief This function sets a value in member boxId
     * @param _boxId New value for member boxId
     */
    eProsima_user_DllExport void boxId(
            int32_t _boxId)
    {
        m_boxId = _boxId;
    }

    /*!
     * @brief This function returns the value of member boxId
     * @return Value of member boxId
     */
    eProsima_user_DllExport int32_t boxId() const
    {
        return m_boxId;
    }

    /*!
     * @brief This function returns a reference to member boxId
     * @return Reference to member boxId
     */
    eProsima_user_DllExport int32_t& boxId()
    {
        return m_boxId;
    }


    /*!
     * @brief This function sets a value in member classId
     * @param _classId New value for member classId
     */
    eProsima_user_DllExport void classId(
            int32_t _classId)
    {
        m_classId = _classId;
    }

    /*!
     * @brief This function returns the value of member classId
     * @return Value of member classId
     */
    eProsima_user_DllExport int32_t classId() const
    {
        return m_classId;
    }

    /*!
     * @brief This function returns a reference to member classId
     * @return Reference to member classId
     */
    eProsima_user_DllExport int32_t& classId()
    {
        return m_classId;
    }



private:

    int16_t m_x{0};
    int16_t m_y{0};
    int16_t m_width{0};
    int16_t m_height{0};
    int32_t m_boxId{0};
    int32_t m_classId{0};

};
/*!
 * @brief This class represents the structure SingleTrackResult defined by the user in the IDL file.
 * @ingroup SingleTrackResult
 */
class SingleTrackResult
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SingleTrackResult()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SingleTrackResult()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SingleTrackResult that will be copied.
     */
    eProsima_user_DllExport SingleTrackResult(
            const SingleTrackResult& x)
    {
                    m_cameraId = x.m_cameraId;

                    m_syncHeader = x.m_syncHeader;

                    m_boxCount = x.m_boxCount;

                    m_box = x.m_box;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SingleTrackResult that will be copied.
     */
    eProsima_user_DllExport SingleTrackResult(
            SingleTrackResult&& x) noexcept
    {
        m_cameraId = std::move(x.m_cameraId);
        m_syncHeader = std::move(x.m_syncHeader);
        m_boxCount = x.m_boxCount;
        m_box = std::move(x.m_box);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SingleTrackResult that will be copied.
     */
    eProsima_user_DllExport SingleTrackResult& operator =(
            const SingleTrackResult& x)
    {

                    m_cameraId = x.m_cameraId;

                    m_syncHeader = x.m_syncHeader;

                    m_boxCount = x.m_boxCount;

                    m_box = x.m_box;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SingleTrackResult that will be copied.
     */
    eProsima_user_DllExport SingleTrackResult& operator =(
            SingleTrackResult&& x) noexcept
    {

        m_cameraId = std::move(x.m_cameraId);
        m_syncHeader = std::move(x.m_syncHeader);
        m_boxCount = x.m_boxCount;
        m_box = std::move(x.m_box);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SingleTrackResult object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SingleTrackResult& x) const
    {
        return (m_cameraId == x.m_cameraId &&
           m_syncHeader == x.m_syncHeader &&
           m_boxCount == x.m_boxCount &&
           m_box == x.m_box);
    }

    /*!
     * @brief Comparison operator.
     * @param x SingleTrackResult object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SingleTrackResult& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member cameraId
     * @param _cameraId New value to be copied in member cameraId
     */
    eProsima_user_DllExport void cameraId(
            const std::string& _cameraId)
    {
        m_cameraId = _cameraId;
    }

    /*!
     * @brief This function moves the value in member cameraId
     * @param _cameraId New value to be moved in member cameraId
     */
    eProsima_user_DllExport void cameraId(
            std::string&& _cameraId)
    {
        m_cameraId = std::move(_cameraId);
    }

    /*!
     * @brief This function returns a constant reference to member cameraId
     * @return Constant reference to member cameraId
     */
    eProsima_user_DllExport const std::string& cameraId() const
    {
        return m_cameraId;
    }

    /*!
     * @brief This function returns a reference to member cameraId
     * @return Reference to member cameraId
     */
    eProsima_user_DllExport std::string& cameraId()
    {
        return m_cameraId;
    }


    /*!
     * @brief This function copies the value in member syncHeader
     * @param _syncHeader New value to be copied in member syncHeader
     */
    eProsima_user_DllExport void syncHeader(
            const std::string& _syncHeader)
    {
        m_syncHeader = _syncHeader;
    }

    /*!
     * @brief This function moves the value in member syncHeader
     * @param _syncHeader New value to be moved in member syncHeader
     */
    eProsima_user_DllExport void syncHeader(
            std::string&& _syncHeader)
    {
        m_syncHeader = std::move(_syncHeader);
    }

    /*!
     * @brief This function returns a constant reference to member syncHeader
     * @return Constant reference to member syncHeader
     */
    eProsima_user_DllExport const std::string& syncHeader() const
    {
        return m_syncHeader;
    }

    /*!
     * @brief This function returns a reference to member syncHeader
     * @return Reference to member syncHeader
     */
    eProsima_user_DllExport std::string& syncHeader()
    {
        return m_syncHeader;
    }


    /*!
     * @brief This function sets a value in member boxCount
     * @param _boxCount New value for member boxCount
     */
    eProsima_user_DllExport void boxCount(
            int32_t _boxCount)
    {
        m_boxCount = _boxCount;
    }

    /*!
     * @brief This function returns the value of member boxCount
     * @return Value of member boxCount
     */
    eProsima_user_DllExport int32_t boxCount() const
    {
        return m_boxCount;
    }

    /*!
     * @brief This function returns a reference to member boxCount
     * @return Reference to member boxCount
     */
    eProsima_user_DllExport int32_t& boxCount()
    {
        return m_boxCount;
    }


    /*!
     * @brief This function copies the value in member box
     * @param _box New value to be copied in member box
     */
    eProsima_user_DllExport void box(
            const BoundingBox& _box)
    {
        m_box = _box;
    }

    /*!
     * @brief This function moves the value in member box
     * @param _box New value to be moved in member box
     */
    eProsima_user_DllExport void box(
            BoundingBox&& _box)
    {
        m_box = std::move(_box);
    }

    /*!
     * @brief This function returns a constant reference to member box
     * @return Constant reference to member box
     */
    eProsima_user_DllExport const BoundingBox& box() const
    {
        return m_box;
    }

    /*!
     * @brief This function returns a reference to member box
     * @return Reference to member box
     */
    eProsima_user_DllExport BoundingBox& box()
    {
        return m_box;
    }



private:

    std::string m_cameraId;
    std::string m_syncHeader;
    int32_t m_boxCount{0};
    BoundingBox m_box;

};

} // namespace detection

} // namespace device

} // namespace casia

#endif // _FAST_DDS_GENERATED_CASIA_DEVICE_DETECTION_SINGLETRACKRESULT_HPP_


