# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('DroneTaskRealTimeStatus.dll')
if __package__ or '.' in __name__:
    from . import _DroneTaskRealTimeStatusWrapper
else:
    import _DroneTaskRealTimeStatusWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_SwigPyIterator

    def value(self):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.SwigPyIterator_swigregister(SwigPyIterator)

FASTCDR_VERSION_MAJOR = _DroneTaskRealTimeStatusWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _DroneTaskRealTimeStatusWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _DroneTaskRealTimeStatusWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _DroneTaskRealTimeStatusWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _DroneTaskRealTimeStatusWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _DroneTaskRealTimeStatusWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _DroneTaskRealTimeStatusWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _DroneTaskRealTimeStatusWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class _GeoPositionSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__GeoPositionSeq

# Register _GeoPositionSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._GeoPositionSeq_swigregister(_GeoPositionSeq)

class GeoPositionSeq(_GeoPositionSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_GeoPositionSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.GeoPositionSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_GeoPositionSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionSeq___getitem__(self, i)

# Register GeoPositionSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.GeoPositionSeq_swigregister(GeoPositionSeq)

class _BaseDeviceStatusSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__BaseDeviceStatusSeq

# Register _BaseDeviceStatusSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._BaseDeviceStatusSeq_swigregister(_BaseDeviceStatusSeq)

class BaseDeviceStatusSeq(_BaseDeviceStatusSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_BaseDeviceStatusSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_BaseDeviceStatusSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusSeq___getitem__(self, i)

# Register BaseDeviceStatusSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.BaseDeviceStatusSeq_swigregister(BaseDeviceStatusSeq)

class _WaypointHeadingParamSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__WaypointHeadingParamSeq

# Register _WaypointHeadingParamSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._WaypointHeadingParamSeq_swigregister(_WaypointHeadingParamSeq)

class WaypointHeadingParamSeq(_WaypointHeadingParamSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaypointHeadingParamSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaypointHeadingParamSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamSeq___getitem__(self, i)

# Register WaypointHeadingParamSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaypointHeadingParamSeq_swigregister(WaypointHeadingParamSeq)

class _WaypointTurnParamSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__WaypointTurnParamSeq

# Register _WaypointTurnParamSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._WaypointTurnParamSeq_swigregister(_WaypointTurnParamSeq)

class WaypointTurnParamSeq(_WaypointTurnParamSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaypointTurnParamSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.WaypointTurnParamSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaypointTurnParamSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamSeq___getitem__(self, i)

# Register WaypointTurnParamSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaypointTurnParamSeq_swigregister(WaypointTurnParamSeq)

class _ActionSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__ActionSeq

# Register _ActionSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._ActionSeq_swigregister(_ActionSeq)

class ActionSeq(_ActionSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_ActionSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.ActionSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_ActionSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.ActionSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.ActionSeq___getitem__(self, i)

# Register ActionSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.ActionSeq_swigregister(ActionSeq)

class _ActionTriggerParamSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__ActionTriggerParamSeq

# Register _ActionTriggerParamSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._ActionTriggerParamSeq_swigregister(_ActionTriggerParamSeq)

class ActionTriggerParamSeq(_ActionTriggerParamSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_ActionTriggerParamSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.ActionTriggerParamSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_ActionTriggerParamSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamSeq___getitem__(self, i)

# Register ActionTriggerParamSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.ActionTriggerParamSeq_swigregister(ActionTriggerParamSeq)

class Action_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___nonzero__(self)

    def __bool__(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___bool__(self)

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___len__(self)

    def __getslice__(self, i, j):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_vector___setitem__(self, *args)

    def pop(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_pop(self)

    def append(self, x):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_append(self, x)

    def empty(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_empty(self)

    def size(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_size(self)

    def swap(self, v):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_swap(self, v)

    def begin(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_begin(self)

    def end(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_end(self)

    def rbegin(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_rbegin(self)

    def rend(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_rend(self)

    def clear(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_clear(self)

    def get_allocator(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_get_allocator(self)

    def pop_back(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_pop_back(self)

    def erase(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_erase(self, *args)

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.Action_vector_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_Action_vector(*args))

    def push_back(self, x):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_push_back(self, x)

    def front(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_front(self)

    def back(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_back(self)

    def assign(self, n, x):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_assign(self, n, x)

    def resize(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_resize(self, *args)

    def insert(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_insert(self, *args)

    def reserve(self, n):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_reserve(self, n)

    def capacity(self):
        return _DroneTaskRealTimeStatusWrapper.Action_vector_capacity(self)
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_Action_vector

# Register Action_vector in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.Action_vector_swigregister(Action_vector)

class _WaypointSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__WaypointSeq

# Register _WaypointSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._WaypointSeq_swigregister(_WaypointSeq)

class WaypointSeq(_WaypointSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaypointSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.WaypointSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaypointSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.WaypointSeq___getitem__(self, i)

# Register WaypointSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaypointSeq_swigregister(WaypointSeq)

class Waypoint_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___nonzero__(self)

    def __bool__(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___bool__(self)

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___len__(self)

    def __getslice__(self, i, j):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector___setitem__(self, *args)

    def pop(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_pop(self)

    def append(self, x):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_append(self, x)

    def empty(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_empty(self)

    def size(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_size(self)

    def swap(self, v):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_swap(self, v)

    def begin(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_begin(self)

    def end(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_end(self)

    def rbegin(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_rbegin(self)

    def rend(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_rend(self)

    def clear(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_clear(self)

    def get_allocator(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_get_allocator(self)

    def pop_back(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_pop_back(self)

    def erase(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_erase(self, *args)

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.Waypoint_vector_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_Waypoint_vector(*args))

    def push_back(self, x):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_push_back(self, x)

    def front(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_front(self)

    def back(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_back(self)

    def assign(self, n, x):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_assign(self, n, x)

    def resize(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_resize(self, *args)

    def insert(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_insert(self, *args)

    def reserve(self, n):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_reserve(self, n)

    def capacity(self):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_vector_capacity(self)
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_Waypoint_vector

# Register Waypoint_vector in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.Waypoint_vector_swigregister(Waypoint_vector)

class _SearchAreaSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__SearchAreaSeq

# Register _SearchAreaSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._SearchAreaSeq_swigregister(_SearchAreaSeq)

class SearchAreaSeq(_SearchAreaSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_SearchAreaSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.SearchAreaSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_SearchAreaSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaSeq___getitem__(self, i)

# Register SearchAreaSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.SearchAreaSeq_swigregister(SearchAreaSeq)

class _GenerateAreaSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__GenerateAreaSeq

# Register _GenerateAreaSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._GenerateAreaSeq_swigregister(_GenerateAreaSeq)

class GenerateAreaSeq(_GenerateAreaSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_GenerateAreaSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.GenerateAreaSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_GenerateAreaSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaSeq___getitem__(self, i)

# Register GenerateAreaSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.GenerateAreaSeq_swigregister(GenerateAreaSeq)

class _WaylineSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__WaylineSeq

# Register _WaylineSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._WaylineSeq_swigregister(_WaylineSeq)

class WaylineSeq(_WaylineSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaylineSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.WaylineSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaylineSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.WaylineSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.WaylineSeq___getitem__(self, i)

# Register WaylineSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaylineSeq_swigregister(WaylineSeq)

class _DroneTaskRealTimeStatusSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete__DroneTaskRealTimeStatusSeq

# Register _DroneTaskRealTimeStatusSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper._DroneTaskRealTimeStatusSeq_swigregister(_DroneTaskRealTimeStatusSeq)

class DroneTaskRealTimeStatusSeq(_DroneTaskRealTimeStatusSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_DroneTaskRealTimeStatusSeq

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusSeq_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_DroneTaskRealTimeStatusSeq(*args))

    def __len__(self):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusSeq___len__(self)

    def __getitem__(self, i):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusSeq___getitem__(self, i)

# Register DroneTaskRealTimeStatusSeq in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusSeq_swigregister(DroneTaskRealTimeStatusSeq)

ExecutionState_EXECUTING = _DroneTaskRealTimeStatusWrapper.ExecutionState_EXECUTING
ExecutionState_COMPLETED = _DroneTaskRealTimeStatusWrapper.ExecutionState_COMPLETED
ExecutionState_ALREADY_CLEARED = _DroneTaskRealTimeStatusWrapper.ExecutionState_ALREADY_CLEARED
ExecutionState_SAVED = _DroneTaskRealTimeStatusWrapper.ExecutionState_SAVED
ExecutionState_FAILED = _DroneTaskRealTimeStatusWrapper.ExecutionState_FAILED
class GeoPosition(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_GeoPosition

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.GeoPosition_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_GeoPosition(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.GeoPosition___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.GeoPosition___ne__(self, x)

    def longitude(self, *args):
        return _DroneTaskRealTimeStatusWrapper.GeoPosition_longitude(self, *args)

    def latitude(self, *args):
        return _DroneTaskRealTimeStatusWrapper.GeoPosition_latitude(self, *args)

    def altitude(self, *args):
        return _DroneTaskRealTimeStatusWrapper.GeoPosition_altitude(self, *args)

# Register GeoPosition in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.GeoPosition_swigregister(GeoPosition)

class BaseDeviceStatus(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_BaseDeviceStatus

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_BaseDeviceStatus(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus___ne__(self, x)

    def entityId(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_entityId(self, *args)

    def taskType(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_taskType(self, *args)

    def executionState(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_executionState(self, *args)

    def executionTimeMs(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_executionTimeMs(self, *args)

    def online(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_online(self, *args)

    def position(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_position(self, *args)

    def elec(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_elec(self, *args)

    def timestamp(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_timestamp(self, *args)

# Register BaseDeviceStatus in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.BaseDeviceStatus_swigregister(BaseDeviceStatus)

TemplateType_WAYPOINT = _DroneTaskRealTimeStatusWrapper.TemplateType_WAYPOINT
TemplateType_MAPPING_2D = _DroneTaskRealTimeStatusWrapper.TemplateType_MAPPING_2D
TemplateType_MAPPING_3D = _DroneTaskRealTimeStatusWrapper.TemplateType_MAPPING_3D
TemplateType_MAPPING_STRIP = _DroneTaskRealTimeStatusWrapper.TemplateType_MAPPING_STRIP
DroneType_M3D_M3TD = _DroneTaskRealTimeStatusWrapper.DroneType_M3D_M3TD
PayloadPosition_POSITION_0 = _DroneTaskRealTimeStatusWrapper.PayloadPosition_POSITION_0
FinishAction_GO_HOME = _DroneTaskRealTimeStatusWrapper.FinishAction_GO_HOME
FinishAction_NO_ACTION = _DroneTaskRealTimeStatusWrapper.FinishAction_NO_ACTION
FinishAction_AUTO_LAND = _DroneTaskRealTimeStatusWrapper.FinishAction_AUTO_LAND
FinishAction_GOTO_FIRST_WAYPOINT = _DroneTaskRealTimeStatusWrapper.FinishAction_GOTO_FIRST_WAYPOINT
RCLostAction_GO_BACK = _DroneTaskRealTimeStatusWrapper.RCLostAction_GO_BACK
RCLostAction_LANDING = _DroneTaskRealTimeStatusWrapper.RCLostAction_LANDING
RCLostAction_HOVER = _DroneTaskRealTimeStatusWrapper.RCLostAction_HOVER
WaypointHeadingMode_FOLLOW_WAYLINE = _DroneTaskRealTimeStatusWrapper.WaypointHeadingMode_FOLLOW_WAYLINE
WaypointHeadingMode_MANUALLY = _DroneTaskRealTimeStatusWrapper.WaypointHeadingMode_MANUALLY
WaypointHeadingMode_FIXED_YAW = _DroneTaskRealTimeStatusWrapper.WaypointHeadingMode_FIXED_YAW
WaypointHeadingMode_SMOOTH_TRANSITION = _DroneTaskRealTimeStatusWrapper.WaypointHeadingMode_SMOOTH_TRANSITION
WaypointHeadingMode_TOWARD_POI = _DroneTaskRealTimeStatusWrapper.WaypointHeadingMode_TOWARD_POI
WaypointTurnMode_COORDINATE_TURN = _DroneTaskRealTimeStatusWrapper.WaypointTurnMode_COORDINATE_TURN
WaypointTurnMode_TO_POINT_AND_STOP_WITH_DISCONTINUITY_CURVATURE = _DroneTaskRealTimeStatusWrapper.WaypointTurnMode_TO_POINT_AND_STOP_WITH_DISCONTINUITY_CURVATURE
WaypointTurnMode_TO_POINT_AND_STOP_WITH_CONTINUITY_CURVATURE = _DroneTaskRealTimeStatusWrapper.WaypointTurnMode_TO_POINT_AND_STOP_WITH_CONTINUITY_CURVATURE
WaypointTurnMode_TO_POINT_AND_PASS_WITH_CONTINUITY_CURVATURE = _DroneTaskRealTimeStatusWrapper.WaypointTurnMode_TO_POINT_AND_PASS_WITH_CONTINUITY_CURVATURE
GimbalPitchMode_MANUAL = _DroneTaskRealTimeStatusWrapper.GimbalPitchMode_MANUAL
GimbalPitchMode_USE_POINT_SETTING = _DroneTaskRealTimeStatusWrapper.GimbalPitchMode_USE_POINT_SETTING
ActionTriggerType_REACH_POINT = _DroneTaskRealTimeStatusWrapper.ActionTriggerType_REACH_POINT
ActionTriggerType_BETWEEN_ADJACENT_POINTS = _DroneTaskRealTimeStatusWrapper.ActionTriggerType_BETWEEN_ADJACENT_POINTS
ActionTriggerType_MULTIPLE_TIMING = _DroneTaskRealTimeStatusWrapper.ActionTriggerType_MULTIPLE_TIMING
ActionTriggerType_MULTIPLE_DISTANCE = _DroneTaskRealTimeStatusWrapper.ActionTriggerType_MULTIPLE_DISTANCE
class WaypointHeadingParam(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaypointHeadingParam

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.WaypointHeadingParam_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaypointHeadingParam(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParam___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParam___ne__(self, x)

    def waypoint_heading_mode(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParam_waypoint_heading_mode(self, *args)

    def waypoint_heading_angle(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParam_waypoint_heading_angle(self, *args)

    def waypoint_poi_point(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParam_waypoint_poi_point(self, *args)

# Register WaypointHeadingParam in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaypointHeadingParam_swigregister(WaypointHeadingParam)

class WaypointTurnParam(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaypointTurnParam

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.WaypointTurnParam_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaypointTurnParam(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParam___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParam___ne__(self, x)

    def waypoint_turn_mode(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParam_waypoint_turn_mode(self, *args)

    def waypoint_turn_damping_dist(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParam_waypoint_turn_damping_dist(self, *args)

    def use_straight_line(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParam_use_straight_line(self, *args)

# Register WaypointTurnParam in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaypointTurnParam_swigregister(WaypointTurnParam)

class Action(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_Action

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.Action_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_Action(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.Action___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.Action___ne__(self, x)

    def action_index(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_action_index(self, *args)

    def hover_time(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_hover_time(self, *args)

    def aircraft_heading(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_aircraft_heading(self, *args)

    def use_global_image_format(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_use_global_image_format(self, *args)

    def image_format(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_image_format(self, *args)

    def gimbal_yaw_rotate_angle(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_gimbal_yaw_rotate_angle(self, *args)

    def gimbal_pitch_rotate_angle(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_gimbal_pitch_rotate_angle(self, *args)

    def zoom(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Action_zoom(self, *args)

# Register Action in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.Action_swigregister(Action)

class ActionTriggerParam(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_ActionTriggerParam

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.ActionTriggerParam_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_ActionTriggerParam(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParam___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParam___ne__(self, x)

    def action_trigger_type(self, *args):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParam_action_trigger_type(self, *args)

    def action_trigger_param(self, *args):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParam_action_trigger_param(self, *args)

# Register ActionTriggerParam in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.ActionTriggerParam_swigregister(ActionTriggerParam)

class Waypoint(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_Waypoint

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.Waypoint_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_Waypoint(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.Waypoint___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.Waypoint___ne__(self, x)

    def index(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_index(self, *args)

    def latitude(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_latitude(self, *args)

    def longitude(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_longitude(self, *args)

    def height(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_height(self, *args)

    def speed(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_speed(self, *args)

    def heading_param(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_heading_param(self, *args)

    def turn_param(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_turn_param(self, *args)

    def gimbal_pitch_angle(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_gimbal_pitch_angle(self, *args)

    def actions(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_actions(self, *args)

    def action_trigger_param(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Waypoint_action_trigger_param(self, *args)

# Register Waypoint in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.Waypoint_swigregister(Waypoint)

class SearchArea(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_SearchArea

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.SearchArea_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_SearchArea(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.SearchArea___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.SearchArea___ne__(self, x)

    def area_name(self, *args):
        return _DroneTaskRealTimeStatusWrapper.SearchArea_area_name(self, *args)

    def area_points(self, *args):
        return _DroneTaskRealTimeStatusWrapper.SearchArea_area_points(self, *args)

# Register SearchArea in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.SearchArea_swigregister(SearchArea)

class GenerateArea(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_GenerateArea

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.GenerateArea_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_GenerateArea(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.GenerateArea___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.GenerateArea___ne__(self, x)

    def area_name(self, *args):
        return _DroneTaskRealTimeStatusWrapper.GenerateArea_area_name(self, *args)

    def area_points(self, *args):
        return _DroneTaskRealTimeStatusWrapper.GenerateArea_area_points(self, *args)

# Register GenerateArea in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.GenerateArea_swigregister(GenerateArea)

class Wayline(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_Wayline

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.Wayline_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_Wayline(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.Wayline___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.Wayline___ne__(self, x)

    def wayline_id(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_wayline_id(self, *args)

    def wayline_name(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_wayline_name(self, *args)

    def template_type(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_template_type(self, *args)

    def drone_type(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_drone_type(self, *args)

    def sub_drone_type(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_sub_drone_type(self, *args)

    def payload_type(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_payload_type(self, *args)

    def payload_position(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_payload_position(self, *args)

    def image_format(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_image_format(self, *args)

    def finish_action(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_finish_action(self, *args)

    def execute_rc_lost_action(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_execute_rc_lost_action(self, *args)

    def global_height(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_global_height(self, *args)

    def auto_flight_speed(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_auto_flight_speed(self, *args)

    def gimbal_pitch_mode(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_gimbal_pitch_mode(self, *args)

    def take_off_ref_point(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_take_off_ref_point(self, *args)

    def global_waypoint_heading_param(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_global_waypoint_heading_param(self, *args)

    def global_waypoint_turn_param(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_global_waypoint_turn_param(self, *args)

    def way_point_list(self, *args):
        return _DroneTaskRealTimeStatusWrapper.Wayline_way_point_list(self, *args)

# Register Wayline in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.Wayline_swigregister(Wayline)

class DroneTaskRealTimeStatus(BaseDeviceStatus):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_DroneTaskRealTimeStatus

    def __init__(self, *args):
        _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_DroneTaskRealTimeStatus(*args))

    def __eq__(self, x):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus___eq__(self, x)

    def __ne__(self, x):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus___ne__(self, x)

    def current_wayline(self, *args):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_current_wayline(self, *args)

    def current_SearchArea(self, *args):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_current_SearchArea(self, *args)

    def current_GenerateArea(self, *args):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_current_GenerateArea(self, *args)

    def drone_state(self, *args):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_drone_state(self, *args)

    def rev1(self, *args):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_rev1(self, *args)

    def rev2(self, *args):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_rev2(self, *args)

    def rev3(self, *args):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_rev3(self, *args)

# Register DroneTaskRealTimeStatus in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatus_swigregister(DroneTaskRealTimeStatus)

FASTDDS_GEN_API_VER = _DroneTaskRealTimeStatusWrapper.FASTDDS_GEN_API_VER
class GeoPositionPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_GeoPositionPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_GeoPositionPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_construct_sample(self, memory)

# Register GeoPositionPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.GeoPositionPubSubType_swigregister(GeoPositionPubSubType)

class BaseDeviceStatusPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_BaseDeviceStatusPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_BaseDeviceStatusPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_construct_sample(self, memory)

# Register BaseDeviceStatusPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.BaseDeviceStatusPubSubType_swigregister(BaseDeviceStatusPubSubType)

class WaypointHeadingParamPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaypointHeadingParamPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaypointHeadingParamPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_construct_sample(self, memory)

# Register WaypointHeadingParamPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaypointHeadingParamPubSubType_swigregister(WaypointHeadingParamPubSubType)

class WaypointTurnParamPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaypointTurnParamPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaypointTurnParamPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_construct_sample(self, memory)

# Register WaypointTurnParamPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaypointTurnParamPubSubType_swigregister(WaypointTurnParamPubSubType)

class ActionPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.ActionPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_ActionPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_ActionPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.ActionPubSubType_construct_sample(self, memory)

# Register ActionPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.ActionPubSubType_swigregister(ActionPubSubType)

class ActionTriggerParamPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_ActionTriggerParamPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_ActionTriggerParamPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_construct_sample(self, memory)

# Register ActionTriggerParamPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.ActionTriggerParamPubSubType_swigregister(ActionTriggerParamPubSubType)

class WaypointPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaypointPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaypointPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.WaypointPubSubType_construct_sample(self, memory)

# Register WaypointPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaypointPubSubType_swigregister(WaypointPubSubType)

class SearchAreaPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_SearchAreaPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_SearchAreaPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_construct_sample(self, memory)

# Register SearchAreaPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.SearchAreaPubSubType_swigregister(SearchAreaPubSubType)

class GenerateAreaPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_GenerateAreaPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_GenerateAreaPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_construct_sample(self, memory)

# Register GenerateAreaPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.GenerateAreaPubSubType_swigregister(GenerateAreaPubSubType)

class WaylinePubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_WaylinePubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_WaylinePubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.WaylinePubSubType_construct_sample(self, memory)

# Register WaylinePubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.WaylinePubSubType_swigregister(WaylinePubSubType)

class DroneTaskRealTimeStatusPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_swiginit(self, _DroneTaskRealTimeStatusWrapper.new_DroneTaskRealTimeStatusPubSubType())
    __swig_destroy__ = _DroneTaskRealTimeStatusWrapper.delete_DroneTaskRealTimeStatusPubSubType

    def serialize(self, data, payload, data_representation):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_compute_key(self, *args)

    def create_data(self):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_create_data(self)

    def delete_data(self, data):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_construct_sample(self, memory)

# Register DroneTaskRealTimeStatusPubSubType in _DroneTaskRealTimeStatusWrapper:
_DroneTaskRealTimeStatusWrapper.DroneTaskRealTimeStatusPubSubType_swigregister(DroneTaskRealTimeStatusPubSubType)



