// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DroneTaskRealTimeStatusCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_DRONETASK_DRONETASKREALTIMESTATUSCDRAUX_HPP
#define FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_DRONETASK_DRONETASKREALTIMESTATUSCDRAUX_HPP

#include "DroneTaskRealTimeStatus.hpp"

constexpr uint32_t casia_device_status_dronetask_Wayline_max_cdr_typesize {1660UL};
constexpr uint32_t casia_device_status_dronetask_Wayline_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dronetask_DroneTaskRealTimeStatus_max_cdr_typesize {4076UL};
constexpr uint32_t casia_device_status_dronetask_DroneTaskRealTimeStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dronetask_WaypointTurnParam_max_cdr_typesize {20UL};
constexpr uint32_t casia_device_status_dronetask_WaypointTurnParam_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_dronetask_GeoPosition_max_cdr_typesize {32UL};
constexpr uint32_t casia_device_status_dronetask_GeoPosition_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dronetask_GenerateArea_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_dronetask_GenerateArea_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dronetask_Waypoint_max_cdr_typesize {376UL};
constexpr uint32_t casia_device_status_dronetask_Waypoint_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dronetask_SearchArea_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_dronetask_SearchArea_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_dronetask_Action_max_cdr_typesize {312UL};
constexpr uint32_t casia_device_status_dronetask_Action_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_dronetask_WaypointHeadingParam_max_cdr_typesize {276UL};
constexpr uint32_t casia_device_status_dronetask_WaypointHeadingParam_max_key_cdr_typesize {0UL};




constexpr uint32_t casia_device_status_dronetask_ActionTriggerParam_max_cdr_typesize {16UL};
constexpr uint32_t casia_device_status_dronetask_ActionTriggerParam_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dronetask_BaseDeviceStatus_max_cdr_typesize {836UL};
constexpr uint32_t casia_device_status_dronetask_BaseDeviceStatus_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::GeoPosition& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::BaseDeviceStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::WaypointHeadingParam& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::WaypointTurnParam& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::Action& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::ActionTriggerParam& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::Waypoint& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::SearchArea& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::GenerateArea& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::Wayline& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dronetask::DroneTaskRealTimeStatus& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_DRONETASK_DRONETASKREALTIMESTATUSCDRAUX_HPP

