// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file WorkModeStatus.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__CASIA_SYSTEM_WORKMODE_WORKMODESTATUS_HPP
#define FAST_DDS_GENERATED__CASIA_SYSTEM_WORKMODE_WORKMODESTATUS_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(WORKMODESTATUS_SOURCE)
#define WORKMODESTATUS_DllAPI __declspec( dllexport )
#else
#define WORKMODESTATUS_DllAPI __declspec( dllimport )
#endif // WORKMODESTATUS_SOURCE
#else
#define WORKMODESTATUS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define WORKMODESTATUS_DllAPI
#endif // _WIN32

namespace casia {

namespace system {

namespace workmode {

/*!
 * @brief This class represents the enumeration WorkMode defined by the user in the IDL file.
 * @ingroup WorkModeStatus
 */
enum class WorkMode : int32_t
{
    EMERGENCY,
    DEBUG,
    NORMAL,
    WARTIME
};
/*!
 * @brief This class represents the structure WorkModeStatus defined by the user in the IDL file.
 * @ingroup WorkModeStatus
 */
class WorkModeStatus
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport WorkModeStatus()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~WorkModeStatus()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object WorkModeStatus that will be copied.
     */
    eProsima_user_DllExport WorkModeStatus(
            const WorkModeStatus& x)
    {
                    m_work_mode = x.m_work_mode;

                    m_reserved_str_1 = x.m_reserved_str_1;

                    m_reserved_str_2 = x.m_reserved_str_2;

                    m_reserved_str_3 = x.m_reserved_str_3;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object WorkModeStatus that will be copied.
     */
    eProsima_user_DllExport WorkModeStatus(
            WorkModeStatus&& x) noexcept
    {
        m_work_mode = x.m_work_mode;
        m_reserved_str_1 = std::move(x.m_reserved_str_1);
        m_reserved_str_2 = std::move(x.m_reserved_str_2);
        m_reserved_str_3 = std::move(x.m_reserved_str_3);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object WorkModeStatus that will be copied.
     */
    eProsima_user_DllExport WorkModeStatus& operator =(
            const WorkModeStatus& x)
    {

                    m_work_mode = x.m_work_mode;

                    m_reserved_str_1 = x.m_reserved_str_1;

                    m_reserved_str_2 = x.m_reserved_str_2;

                    m_reserved_str_3 = x.m_reserved_str_3;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object WorkModeStatus that will be copied.
     */
    eProsima_user_DllExport WorkModeStatus& operator =(
            WorkModeStatus&& x) noexcept
    {

        m_work_mode = x.m_work_mode;
        m_reserved_str_1 = std::move(x.m_reserved_str_1);
        m_reserved_str_2 = std::move(x.m_reserved_str_2);
        m_reserved_str_3 = std::move(x.m_reserved_str_3);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x WorkModeStatus object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const WorkModeStatus& x) const
    {
        return (m_work_mode == x.m_work_mode &&
           m_reserved_str_1 == x.m_reserved_str_1 &&
           m_reserved_str_2 == x.m_reserved_str_2 &&
           m_reserved_str_3 == x.m_reserved_str_3);
    }

    /*!
     * @brief Comparison operator.
     * @param x WorkModeStatus object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const WorkModeStatus& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member work_mode
     * @param _work_mode New value for member work_mode
     */
    eProsima_user_DllExport void work_mode(
            WorkMode _work_mode)
    {
        m_work_mode = _work_mode;
    }

    /*!
     * @brief This function returns the value of member work_mode
     * @return Value of member work_mode
     */
    eProsima_user_DllExport WorkMode work_mode() const
    {
        return m_work_mode;
    }

    /*!
     * @brief This function returns a reference to member work_mode
     * @return Reference to member work_mode
     */
    eProsima_user_DllExport WorkMode& work_mode()
    {
        return m_work_mode;
    }


    /*!
     * @brief This function copies the value in member reserved_str_1
     * @param _reserved_str_1 New value to be copied in member reserved_str_1
     */
    eProsima_user_DllExport void reserved_str_1(
            const std::string& _reserved_str_1)
    {
        m_reserved_str_1 = _reserved_str_1;
    }

    /*!
     * @brief This function moves the value in member reserved_str_1
     * @param _reserved_str_1 New value to be moved in member reserved_str_1
     */
    eProsima_user_DllExport void reserved_str_1(
            std::string&& _reserved_str_1)
    {
        m_reserved_str_1 = std::move(_reserved_str_1);
    }

    /*!
     * @brief This function returns a constant reference to member reserved_str_1
     * @return Constant reference to member reserved_str_1
     */
    eProsima_user_DllExport const std::string& reserved_str_1() const
    {
        return m_reserved_str_1;
    }

    /*!
     * @brief This function returns a reference to member reserved_str_1
     * @return Reference to member reserved_str_1
     */
    eProsima_user_DllExport std::string& reserved_str_1()
    {
        return m_reserved_str_1;
    }


    /*!
     * @brief This function copies the value in member reserved_str_2
     * @param _reserved_str_2 New value to be copied in member reserved_str_2
     */
    eProsima_user_DllExport void reserved_str_2(
            const std::string& _reserved_str_2)
    {
        m_reserved_str_2 = _reserved_str_2;
    }

    /*!
     * @brief This function moves the value in member reserved_str_2
     * @param _reserved_str_2 New value to be moved in member reserved_str_2
     */
    eProsima_user_DllExport void reserved_str_2(
            std::string&& _reserved_str_2)
    {
        m_reserved_str_2 = std::move(_reserved_str_2);
    }

    /*!
     * @brief This function returns a constant reference to member reserved_str_2
     * @return Constant reference to member reserved_str_2
     */
    eProsima_user_DllExport const std::string& reserved_str_2() const
    {
        return m_reserved_str_2;
    }

    /*!
     * @brief This function returns a reference to member reserved_str_2
     * @return Reference to member reserved_str_2
     */
    eProsima_user_DllExport std::string& reserved_str_2()
    {
        return m_reserved_str_2;
    }


    /*!
     * @brief This function copies the value in member reserved_str_3
     * @param _reserved_str_3 New value to be copied in member reserved_str_3
     */
    eProsima_user_DllExport void reserved_str_3(
            const std::string& _reserved_str_3)
    {
        m_reserved_str_3 = _reserved_str_3;
    }

    /*!
     * @brief This function moves the value in member reserved_str_3
     * @param _reserved_str_3 New value to be moved in member reserved_str_3
     */
    eProsima_user_DllExport void reserved_str_3(
            std::string&& _reserved_str_3)
    {
        m_reserved_str_3 = std::move(_reserved_str_3);
    }

    /*!
     * @brief This function returns a constant reference to member reserved_str_3
     * @return Constant reference to member reserved_str_3
     */
    eProsima_user_DllExport const std::string& reserved_str_3() const
    {
        return m_reserved_str_3;
    }

    /*!
     * @brief This function returns a reference to member reserved_str_3
     * @return Reference to member reserved_str_3
     */
    eProsima_user_DllExport std::string& reserved_str_3()
    {
        return m_reserved_str_3;
    }



private:

    WorkMode m_work_mode{WorkMode::EMERGENCY};
    std::string m_reserved_str_1;
    std::string m_reserved_str_2;
    std::string m_reserved_str_3;

};

} // namespace workmode

} // namespace system

} // namespace casia

#endif // _FAST_DDS_GENERATED_CASIA_SYSTEM_WORKMODE_WORKMODESTATUS_HPP_


