// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file EntityRealTimeStatusCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_WEAPONSTATUS_ENTITYREALTIMESTATUSCDRAUX_HPP
#define FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_WEAPONSTATUS_ENTITYREALTIMESTATUSCDRAUX_HPP

#include "EntityRealTimeStatus.hpp"

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_DroneRealTimeStatus_max_cdr_typesize {3840UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_DroneRealTimeStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_Wayline_max_cdr_typesize {1660UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_Wayline_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_DongleInfoInDock_max_cdr_typesize {820UL};
constexpr uint32_t casia_device_status_Dock2Status_DongleInfoInDock_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_DroneCameraStatus_max_cdr_typesize {544UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_DroneCameraStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_MunitionStatus_MunitionRealTimeStatus_max_cdr_typesize {1136UL};
constexpr uint32_t casia_device_status_MunitionStatus_MunitionRealTimeStatus_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_DroneBatteryMaintenanceInfo_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_Dock2Status_DroneBatteryMaintenanceInfo_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_DroneChargeState_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_Dock2Status_DroneChargeState_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_ESIMInfo_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_Dock2Status_ESIMInfo_max_key_cdr_typesize {0UL};





constexpr uint32_t casia_device_status_Dock2Status_PositionStateInDock_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_Dock2Status_PositionStateInDock_max_key_cdr_typesize {0UL};




constexpr uint32_t casia_device_status_Dock2Status_StorageCapacity_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_Dock2Status_StorageCapacity_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_USVStatus_USVRealTimeStatus_max_cdr_typesize {1508UL};
constexpr uint32_t casia_device_status_USVStatus_USVRealTimeStatus_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_Dock2Status_CameraList_max_cdr_typesize {280UL};
constexpr uint32_t casia_device_status_Dock2Status_CameraList_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_AirConditioner_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_Dock2Status_AirConditioner_max_key_cdr_typesize {0UL};





constexpr uint32_t casia_device_status_Dock2Status_LiveStatus_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_Dock2Status_LiveStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_ObstacleAvoidance_max_cdr_typesize {16UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_ObstacleAvoidance_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_JammerStatus_JammerRealTimeStatus_max_cdr_typesize {1144UL};
constexpr uint32_t casia_device_status_JammerStatus_JammerRealTimeStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_USVStatus_USVInfo_max_cdr_typesize {48UL};
constexpr uint32_t casia_device_status_USVStatus_USVInfo_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_DroneTaskRealTimeStatus_max_cdr_typesize {4104UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_DroneTaskRealTimeStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_WaypointTurnParam_max_cdr_typesize {20UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_WaypointTurnParam_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_BaseStatus_GeoPosition_max_cdr_typesize {32UL};
constexpr uint32_t casia_device_status_BaseStatus_GeoPosition_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_SubDevice_max_cdr_typesize {532UL};
constexpr uint32_t casia_device_status_Dock2Status_SubDevice_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_EsimInfo_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_EsimInfo_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_BaseStatus_BaseDeviceStatus_max_cdr_typesize {1120UL};
constexpr uint32_t casia_device_status_BaseStatus_BaseDeviceStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_WirelessLink_max_cdr_typesize {56UL};
constexpr uint32_t casia_device_status_Dock2Status_WirelessLink_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_CameraWatermarkSettings_max_cdr_typesize {292UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_CameraWatermarkSettings_max_key_cdr_typesize {0UL};




constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_TemperaturePoint_max_cdr_typesize {32UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_TemperaturePoint_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_LaserStatus_LaserRealTimeStatus_max_cdr_typesize {1136UL};
constexpr uint32_t casia_device_status_LaserStatus_LaserRealTimeStatus_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_ControlSourceNode_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_ControlSourceNode_max_key_cdr_typesize {0UL};






constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_BatteryStatus_max_cdr_typesize {28UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_BatteryStatus_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_DeviceList_max_cdr_typesize {280UL};
constexpr uint32_t casia_device_status_Dock2Status_DeviceList_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_ModelStatus_ResourceUsage_max_cdr_typesize {48UL};
constexpr uint32_t casia_device_status_ModelStatus_ResourceUsage_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_MaintainStatusItemInDrone_max_cdr_typesize {32UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_MaintainStatusItemInDrone_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_MaintainStatusInDock_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_Dock2Status_MaintainStatusInDock_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_StorageInfo_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_StorageInfo_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_RTCMInfo_max_cdr_typesize {792UL};
constexpr uint32_t casia_device_status_Dock2Status_RTCMInfo_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_WaypointHeadingParam_max_cdr_typesize {276UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_WaypointHeadingParam_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_Battery_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_Dock2Status_Battery_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_MaintainStatusItemInDock_max_cdr_typesize {28UL};
constexpr uint32_t casia_device_status_Dock2Status_MaintainStatusItemInDock_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_TypeSubtypeGimbalIndex_max_cdr_typesize {304UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_TypeSubtypeGimbalIndex_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_Dock2Status_VideoList_max_cdr_typesize {532UL};
constexpr uint32_t casia_device_status_Dock2Status_VideoList_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_MaintainStatusInDrone_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_MaintainStatusInDrone_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_USVStatus_USVPTZStatus_max_cdr_typesize {56UL};
constexpr uint32_t casia_device_status_USVStatus_USVPTZStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_Dock2RealTimeStatus_max_cdr_typesize {3836UL};
constexpr uint32_t casia_device_status_Dock2Status_Dock2RealTimeStatus_max_key_cdr_typesize {0UL};





constexpr uint32_t casia_device_status_Dock2Status_AlternateLandPoint_max_cdr_typesize {48UL};
constexpr uint32_t casia_device_status_Dock2Status_AlternateLandPoint_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_SdrNode_max_cdr_typesize {268UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_SdrNode_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_ModelStatus_ModelRealTimeStatus_max_cdr_typesize {1432UL};
constexpr uint32_t casia_device_status_ModelStatus_ModelRealTimeStatus_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_Waypoint_max_cdr_typesize {376UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_Waypoint_max_key_cdr_typesize {0UL};




constexpr uint32_t casia_device_status_Dock2Status_CenterNode_max_cdr_typesize {268UL};
constexpr uint32_t casia_device_status_Dock2Status_CenterNode_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_BatteryInfo_max_cdr_typesize {556UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_BatteryInfo_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_PositionStateInDrone_max_cdr_typesize {20UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_PositionStateInDrone_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_highFreqRealTimeStatus_max_cdr_typesize {1720UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_highFreqRealTimeStatus_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_DongleInfoInDrone_max_cdr_typesize {820UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_DongleInfoInDrone_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_CameraStatus_CameraRealTimeStatus_max_cdr_typesize {1256UL};
constexpr uint32_t casia_device_status_CameraStatus_CameraRealTimeStatus_max_key_cdr_typesize {0UL};





constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_SearchArea_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_SearchArea_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_RadarStatus_RadarRealTimeStatus_max_cdr_typesize {1468UL};
constexpr uint32_t casia_device_status_RadarStatus_RadarRealTimeStatus_max_key_cdr_typesize {0UL};








constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_Action_max_cdr_typesize {312UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_Action_max_key_cdr_typesize {0UL};





constexpr uint32_t casia_device_status_Dock2Status_WirelessLinkTopoInDock_max_cdr_typesize {396UL};
constexpr uint32_t casia_device_status_Dock2Status_WirelessLinkTopoInDock_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_MediaFileDetail_max_cdr_typesize {8UL};
constexpr uint32_t casia_device_status_Dock2Status_MediaFileDetail_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_SIMInfo_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_Dock2Status_SIMInfo_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_ActionTriggerParam_max_cdr_typesize {16UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_ActionTriggerParam_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_WeaponStatus_WeaponRealTimeStatus_max_cdr_typesize {1420UL};
constexpr uint32_t casia_device_status_WeaponStatus_WeaponRealTimeStatus_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_Dock2Status_BackupBattery_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_Dock2Status_BackupBattery_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_LiveCapacity_max_cdr_typesize {20UL};
constexpr uint32_t casia_device_status_Dock2Status_LiveCapacity_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_LiveviewWorldRegion_max_cdr_typesize {20UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_LiveviewWorldRegion_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_LeafNode_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_Dock2Status_LeafNode_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_Dock2Status_LiveStatusItem_max_cdr_typesize {536UL};
constexpr uint32_t casia_device_status_Dock2Status_LiveStatusItem_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_GenerateArea_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneTaskStatus_GenerateArea_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_IrMeteringArea_max_cdr_typesize {112UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_IrMeteringArea_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_Dock2Status_NetworkState_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_Dock2Status_NetworkState_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_WirelessLinkTopoInDrone_max_cdr_typesize {312UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_WirelessLinkTopoInDrone_max_key_cdr_typesize {0UL};




constexpr uint32_t casia_device_status_CameraStatus_PTZStatus_max_cdr_typesize {32UL};
constexpr uint32_t casia_device_status_CameraStatus_PTZStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_CameraStatus_FOVStatus_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_CameraStatus_FOVStatus_max_key_cdr_typesize {0UL};





constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_SimInfo_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_DroneGeneralStatus_DroneStatus_SimInfo_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::BaseStatus::GeoPosition& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::BaseStatus::BaseDeviceStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::CameraStatus::PTZStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::CameraStatus::FOVStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::CameraStatus::CameraRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::ModelStatus::ResourceUsage& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::ModelStatus::ModelRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::RadarStatus::RadarRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::RTCMInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::CenterNode& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::LeafNode& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::WirelessLinkTopoInDock& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::AirConditioner& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::ESIMInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::SIMInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::DongleInfoInDock& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::Battery& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::DroneBatteryMaintenanceInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::MaintainStatusItemInDock& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::MaintainStatusInDock& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::PositionStateInDock& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::DroneChargeState& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::BackupBattery& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::AlternateLandPoint& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::StorageCapacity& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::VideoList& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::CameraList& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::DeviceList& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::LiveCapacity& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::LiveStatusItem& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::LiveStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::WirelessLink& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::MediaFileDetail& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::NetworkState& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::SubDevice& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::Dock2Status::Dock2RealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::WaypointHeadingParam& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::WaypointTurnParam& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::Action& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::ActionTriggerParam& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::Waypoint& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::SearchArea& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::GenerateArea& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::Wayline& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneTaskStatus::DroneTaskRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::SdrNode& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::ControlSourceNode& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::WirelessLinkTopoInDrone& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::LiveviewWorldRegion& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::TemperaturePoint& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::IrMeteringArea& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::EsimInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::SimInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::DongleInfoInDrone& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::MaintainStatusItemInDrone& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::MaintainStatusInDrone& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::TypeSubtypeGimbalIndex& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::PositionStateInDrone& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::StorageInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::BatteryInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::BatteryStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::ObstacleAvoidance& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::CameraWatermarkSettings& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::DroneCameraStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::DroneRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::DroneGeneralStatus::DroneStatus::highFreqRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::USVStatus::USVPTZStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::USVStatus::USVInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::USVStatus::USVRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::JammerStatus::JammerRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::LaserStatus::LaserRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::MunitionStatus::MunitionRealTimeStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::WeaponStatus::WeaponRealTimeStatus& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_WEAPONSTATUS_ENTITYREALTIMESTATUSCDRAUX_HPP

