syntax = "proto3";

package modelPkg;

import "component/aliases.proto";
import "component/ontology.proto";
import "component/health.proto";
import "component/online.proto";
import "component/resources.proto";
import "component/tasks.proto";
import "component/taskCatalog.proto";
import "component/modelParameters.proto";
import "component/modelStatus.proto";
import "component/deployment.proto";
import "component/production.proto";
import "component/relationship.proto";

message Status {
  string platform_activity = 1;// 活动描述字符串，例如 "RECONNAISSANCE"（侦察）、"INTERDICTION"（拦截）、"RETURN TO BASE (RTB)"（返航）、"PREPARING FOR LAUNCH"（准备发射）
  string role = 2;// 角色描述字符串，例如 "Team Member"、"Commander"
  int32 device_state = 3;//设备状态枚举：0(待机)、1(上电)、2(执行)、3(未知)
}

message Indicators{
  bool simulated = 1;	//是否为仿真实体。
  bool exercise = 2;	//是否为演习实体。
  bool emergency = 3;	//是否为紧急实体。
  bool c2 = 4;			//是否为指挥控制实体。
  bool egressable = 5;	//是否应被导出到外部源。
  bool starred = 6;		//是否被用户全局标记。
}

message ModelEntity {
  string entity_id = 1;
  uint64 is_live = 2;
  string created_time = 3;
  string expiry_time = 4;
  bool no_expiry = 5;
  string description = 6;
  string type = 7;
  string place = 8;
  string property = 9;
  Status status = 10;
  Indicators indicators = 11;
  uint64 ttl = 12;
  
  aliasesPkg.Aliases aliases = 13;
  ontologyPkg.Ontology ontology = 14;
  healthPkg.Health health = 15;
  onlinePkg.Online online = 16;
  resourcesPkg.Resources resources = 17;
  tasksPkg.Tasks tasks = 18;
  taskCatalogPkg.TaskCatalog task_catalog = 19;
  modelParametersPkg.ModelParameters model_parameters = 20;
  modelStatusPkg.ModelStatus model_status = 21;
  deploymentPkg.Deployment deployment = 22;
  productionPkg.Production production = 23;
  relationshipPkg.Relationship relationship = 24;
}