# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('MultiTrackResult.dll')
if __package__ or '.' in __name__:
    from . import _MultiTrackResultWrapper
else:
    import _MultiTrackResultWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete_SwigPyIterator

    def value(self):
        return _MultiTrackResultWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _MultiTrackResultWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _MultiTrackResultWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _MultiTrackResultWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _MultiTrackResultWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _MultiTrackResultWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _MultiTrackResultWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _MultiTrackResultWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _MultiTrackResultWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _MultiTrackResultWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _MultiTrackResultWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _MultiTrackResultWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _MultiTrackResultWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _MultiTrackResultWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _MultiTrackResultWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _MultiTrackResultWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.SwigPyIterator_swigregister(SwigPyIterator)

FASTCDR_VERSION_MAJOR = _MultiTrackResultWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _MultiTrackResultWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _MultiTrackResultWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _MultiTrackResultWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _MultiTrackResultWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _MultiTrackResultWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _MultiTrackResultWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _MultiTrackResultWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class _BoundingBoxSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete__BoundingBoxSeq

# Register _BoundingBoxSeq in _MultiTrackResultWrapper:
_MultiTrackResultWrapper._BoundingBoxSeq_swigregister(_BoundingBoxSeq)

class BoundingBoxSeq(_BoundingBoxSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete_BoundingBoxSeq

    def __init__(self, *args):
        _MultiTrackResultWrapper.BoundingBoxSeq_swiginit(self, _MultiTrackResultWrapper.new_BoundingBoxSeq(*args))

    def __len__(self):
        return _MultiTrackResultWrapper.BoundingBoxSeq___len__(self)

    def __getitem__(self, i):
        return _MultiTrackResultWrapper.BoundingBoxSeq___getitem__(self, i)

# Register BoundingBoxSeq in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.BoundingBoxSeq_swigregister(BoundingBoxSeq)

class _SingleTrackResultSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete__SingleTrackResultSeq

# Register _SingleTrackResultSeq in _MultiTrackResultWrapper:
_MultiTrackResultWrapper._SingleTrackResultSeq_swigregister(_SingleTrackResultSeq)

class SingleTrackResultSeq(_SingleTrackResultSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete_SingleTrackResultSeq

    def __init__(self, *args):
        _MultiTrackResultWrapper.SingleTrackResultSeq_swiginit(self, _MultiTrackResultWrapper.new_SingleTrackResultSeq(*args))

    def __len__(self):
        return _MultiTrackResultWrapper.SingleTrackResultSeq___len__(self)

    def __getitem__(self, i):
        return _MultiTrackResultWrapper.SingleTrackResultSeq___getitem__(self, i)

# Register SingleTrackResultSeq in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.SingleTrackResultSeq_swigregister(SingleTrackResultSeq)

class BoundingBox_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MultiTrackResultWrapper.BoundingBox_vector___nonzero__(self)

    def __bool__(self):
        return _MultiTrackResultWrapper.BoundingBox_vector___bool__(self)

    def __len__(self):
        return _MultiTrackResultWrapper.BoundingBox_vector___len__(self)

    def __getslice__(self, i, j):
        return _MultiTrackResultWrapper.BoundingBox_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MultiTrackResultWrapper.BoundingBox_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_vector___setitem__(self, *args)

    def pop(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_pop(self)

    def append(self, x):
        return _MultiTrackResultWrapper.BoundingBox_vector_append(self, x)

    def empty(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_empty(self)

    def size(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_size(self)

    def swap(self, v):
        return _MultiTrackResultWrapper.BoundingBox_vector_swap(self, v)

    def begin(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_begin(self)

    def end(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_end(self)

    def rbegin(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_rbegin(self)

    def rend(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_rend(self)

    def clear(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_clear(self)

    def get_allocator(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_get_allocator(self)

    def pop_back(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_pop_back(self)

    def erase(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_vector_erase(self, *args)

    def __init__(self, *args):
        _MultiTrackResultWrapper.BoundingBox_vector_swiginit(self, _MultiTrackResultWrapper.new_BoundingBox_vector(*args))

    def push_back(self, x):
        return _MultiTrackResultWrapper.BoundingBox_vector_push_back(self, x)

    def front(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_front(self)

    def back(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_back(self)

    def assign(self, n, x):
        return _MultiTrackResultWrapper.BoundingBox_vector_assign(self, n, x)

    def resize(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_vector_resize(self, *args)

    def insert(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_vector_insert(self, *args)

    def reserve(self, n):
        return _MultiTrackResultWrapper.BoundingBox_vector_reserve(self, n)

    def capacity(self):
        return _MultiTrackResultWrapper.BoundingBox_vector_capacity(self)
    __swig_destroy__ = _MultiTrackResultWrapper.delete_BoundingBox_vector

# Register BoundingBox_vector in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.BoundingBox_vector_swigregister(BoundingBox_vector)

class _MultiTrackResultSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete__MultiTrackResultSeq

# Register _MultiTrackResultSeq in _MultiTrackResultWrapper:
_MultiTrackResultWrapper._MultiTrackResultSeq_swigregister(_MultiTrackResultSeq)

class MultiTrackResultSeq(_MultiTrackResultSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete_MultiTrackResultSeq

    def __init__(self, *args):
        _MultiTrackResultWrapper.MultiTrackResultSeq_swiginit(self, _MultiTrackResultWrapper.new_MultiTrackResultSeq(*args))

    def __len__(self):
        return _MultiTrackResultWrapper.MultiTrackResultSeq___len__(self)

    def __getitem__(self, i):
        return _MultiTrackResultWrapper.MultiTrackResultSeq___getitem__(self, i)

# Register MultiTrackResultSeq in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.MultiTrackResultSeq_swigregister(MultiTrackResultSeq)

class BoundingBox(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete_BoundingBox

    def __init__(self, *args):
        _MultiTrackResultWrapper.BoundingBox_swiginit(self, _MultiTrackResultWrapper.new_BoundingBox(*args))

    def __eq__(self, x):
        return _MultiTrackResultWrapper.BoundingBox___eq__(self, x)

    def __ne__(self, x):
        return _MultiTrackResultWrapper.BoundingBox___ne__(self, x)

    def x(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_x(self, *args)

    def y(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_y(self, *args)

    def width(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_width(self, *args)

    def height(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_height(self, *args)

    def boxId(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_boxId(self, *args)

    def classId(self, *args):
        return _MultiTrackResultWrapper.BoundingBox_classId(self, *args)

# Register BoundingBox in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.BoundingBox_swigregister(BoundingBox)

class SingleTrackResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete_SingleTrackResult

    def __init__(self, *args):
        _MultiTrackResultWrapper.SingleTrackResult_swiginit(self, _MultiTrackResultWrapper.new_SingleTrackResult(*args))

    def __eq__(self, x):
        return _MultiTrackResultWrapper.SingleTrackResult___eq__(self, x)

    def __ne__(self, x):
        return _MultiTrackResultWrapper.SingleTrackResult___ne__(self, x)

    def cameraId(self, *args):
        return _MultiTrackResultWrapper.SingleTrackResult_cameraId(self, *args)

    def syncHeader(self, *args):
        return _MultiTrackResultWrapper.SingleTrackResult_syncHeader(self, *args)

    def boxCount(self, *args):
        return _MultiTrackResultWrapper.SingleTrackResult_boxCount(self, *args)

    def box(self, *args):
        return _MultiTrackResultWrapper.SingleTrackResult_box(self, *args)

# Register SingleTrackResult in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.SingleTrackResult_swigregister(SingleTrackResult)

class MultiTrackResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MultiTrackResultWrapper.delete_MultiTrackResult

    def __init__(self, *args):
        _MultiTrackResultWrapper.MultiTrackResult_swiginit(self, _MultiTrackResultWrapper.new_MultiTrackResult(*args))

    def __eq__(self, x):
        return _MultiTrackResultWrapper.MultiTrackResult___eq__(self, x)

    def __ne__(self, x):
        return _MultiTrackResultWrapper.MultiTrackResult___ne__(self, x)

    def cameraId(self, *args):
        return _MultiTrackResultWrapper.MultiTrackResult_cameraId(self, *args)

    def syncHeader(self, *args):
        return _MultiTrackResultWrapper.MultiTrackResult_syncHeader(self, *args)

    def boxCount(self, *args):
        return _MultiTrackResultWrapper.MultiTrackResult_boxCount(self, *args)

    def boxes(self, *args):
        return _MultiTrackResultWrapper.MultiTrackResult_boxes(self, *args)

# Register MultiTrackResult in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.MultiTrackResult_swigregister(MultiTrackResult)

FASTDDS_GEN_API_VER = _MultiTrackResultWrapper.FASTDDS_GEN_API_VER
class BoundingBoxPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _MultiTrackResultWrapper.BoundingBoxPubSubType_swiginit(self, _MultiTrackResultWrapper.new_BoundingBoxPubSubType())
    __swig_destroy__ = _MultiTrackResultWrapper.delete_BoundingBoxPubSubType

    def serialize(self, data, payload, data_representation):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_compute_key(self, *args)

    def create_data(self):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_create_data(self)

    def delete_data(self, data):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _MultiTrackResultWrapper.BoundingBoxPubSubType_construct_sample(self, memory)

# Register BoundingBoxPubSubType in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.BoundingBoxPubSubType_swigregister(BoundingBoxPubSubType)

class SingleTrackResultPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _MultiTrackResultWrapper.SingleTrackResultPubSubType_swiginit(self, _MultiTrackResultWrapper.new_SingleTrackResultPubSubType())
    __swig_destroy__ = _MultiTrackResultWrapper.delete_SingleTrackResultPubSubType

    def serialize(self, data, payload, data_representation):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_compute_key(self, *args)

    def create_data(self):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_create_data(self)

    def delete_data(self, data):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _MultiTrackResultWrapper.SingleTrackResultPubSubType_construct_sample(self, memory)

# Register SingleTrackResultPubSubType in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.SingleTrackResultPubSubType_swigregister(SingleTrackResultPubSubType)

class MultiTrackResultPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _MultiTrackResultWrapper.MultiTrackResultPubSubType_swiginit(self, _MultiTrackResultWrapper.new_MultiTrackResultPubSubType())
    __swig_destroy__ = _MultiTrackResultWrapper.delete_MultiTrackResultPubSubType

    def serialize(self, data, payload, data_representation):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_compute_key(self, *args)

    def create_data(self):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_create_data(self)

    def delete_data(self, data):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _MultiTrackResultWrapper.MultiTrackResultPubSubType_construct_sample(self, memory)

# Register MultiTrackResultPubSubType in _MultiTrackResultWrapper:
_MultiTrackResultWrapper.MultiTrackResultPubSubType_swigregister(MultiTrackResultPubSubType)



