# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('AlarmEvent.dll')
if __package__ or '.' in __name__:
    from . import _AlarmEventWrapper
else:
    import _AlarmEventWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_SwigPyIterator

    def value(self):
        return _AlarmEventWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _AlarmEventWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _AlarmEventWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _AlarmEventWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _AlarmEventWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _AlarmEventWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _AlarmEventWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _AlarmEventWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _AlarmEventWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _AlarmEventWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _AlarmEventWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _AlarmEventWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _AlarmEventWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _AlarmEventWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _AlarmEventWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _AlarmEventWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _AlarmEventWrapper:
_AlarmEventWrapper.SwigPyIterator_swigregister(SwigPyIterator)

FASTCDR_VERSION_MAJOR = _AlarmEventWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _AlarmEventWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _AlarmEventWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _AlarmEventWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _AlarmEventWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _AlarmEventWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _AlarmEventWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _AlarmEventWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class string_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _AlarmEventWrapper.string_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _AlarmEventWrapper.string_vector___nonzero__(self)

    def __bool__(self):
        return _AlarmEventWrapper.string_vector___bool__(self)

    def __len__(self):
        return _AlarmEventWrapper.string_vector___len__(self)

    def __getslice__(self, i, j):
        return _AlarmEventWrapper.string_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _AlarmEventWrapper.string_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _AlarmEventWrapper.string_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _AlarmEventWrapper.string_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _AlarmEventWrapper.string_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _AlarmEventWrapper.string_vector___setitem__(self, *args)

    def pop(self):
        return _AlarmEventWrapper.string_vector_pop(self)

    def append(self, x):
        return _AlarmEventWrapper.string_vector_append(self, x)

    def empty(self):
        return _AlarmEventWrapper.string_vector_empty(self)

    def size(self):
        return _AlarmEventWrapper.string_vector_size(self)

    def swap(self, v):
        return _AlarmEventWrapper.string_vector_swap(self, v)

    def begin(self):
        return _AlarmEventWrapper.string_vector_begin(self)

    def end(self):
        return _AlarmEventWrapper.string_vector_end(self)

    def rbegin(self):
        return _AlarmEventWrapper.string_vector_rbegin(self)

    def rend(self):
        return _AlarmEventWrapper.string_vector_rend(self)

    def clear(self):
        return _AlarmEventWrapper.string_vector_clear(self)

    def get_allocator(self):
        return _AlarmEventWrapper.string_vector_get_allocator(self)

    def pop_back(self):
        return _AlarmEventWrapper.string_vector_pop_back(self)

    def erase(self, *args):
        return _AlarmEventWrapper.string_vector_erase(self, *args)

    def __init__(self, *args):
        _AlarmEventWrapper.string_vector_swiginit(self, _AlarmEventWrapper.new_string_vector(*args))

    def push_back(self, x):
        return _AlarmEventWrapper.string_vector_push_back(self, x)

    def front(self):
        return _AlarmEventWrapper.string_vector_front(self)

    def back(self):
        return _AlarmEventWrapper.string_vector_back(self)

    def assign(self, n, x):
        return _AlarmEventWrapper.string_vector_assign(self, n, x)

    def resize(self, *args):
        return _AlarmEventWrapper.string_vector_resize(self, *args)

    def insert(self, *args):
        return _AlarmEventWrapper.string_vector_insert(self, *args)

    def reserve(self, n):
        return _AlarmEventWrapper.string_vector_reserve(self, n)

    def capacity(self):
        return _AlarmEventWrapper.string_vector_capacity(self)
    __swig_destroy__ = _AlarmEventWrapper.delete_string_vector

# Register string_vector in _AlarmEventWrapper:
_AlarmEventWrapper.string_vector_swigregister(string_vector)

class _BaseEventSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete__BaseEventSeq

# Register _BaseEventSeq in _AlarmEventWrapper:
_AlarmEventWrapper._BaseEventSeq_swigregister(_BaseEventSeq)

class BaseEventSeq(_BaseEventSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_BaseEventSeq

    def __init__(self, *args):
        _AlarmEventWrapper.BaseEventSeq_swiginit(self, _AlarmEventWrapper.new_BaseEventSeq(*args))

    def __len__(self):
        return _AlarmEventWrapper.BaseEventSeq___len__(self)

    def __getitem__(self, i):
        return _AlarmEventWrapper.BaseEventSeq___getitem__(self, i)

# Register BaseEventSeq in _AlarmEventWrapper:
_AlarmEventWrapper.BaseEventSeq_swigregister(BaseEventSeq)

EventSeverity_INFO = _AlarmEventWrapper.EventSeverity_INFO
EventSeverity_WARNING = _AlarmEventWrapper.EventSeverity_WARNING
EventSeverity_ERROR_ = _AlarmEventWrapper.EventSeverity_ERROR_
EventSeverity_CRITICAL = _AlarmEventWrapper.EventSeverity_CRITICAL
EventSourceType_SYSTEM = _AlarmEventWrapper.EventSourceType_SYSTEM
EventSourceType_DEVICE = _AlarmEventWrapper.EventSourceType_DEVICE
EventSourceType_USER = _AlarmEventWrapper.EventSourceType_USER
EventSourceType_TASK = _AlarmEventWrapper.EventSourceType_TASK
EventSourceType_TRACK = _AlarmEventWrapper.EventSourceType_TRACK
class BaseEvent(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_BaseEvent

    def __init__(self, *args):
        _AlarmEventWrapper.BaseEvent_swiginit(self, _AlarmEventWrapper.new_BaseEvent(*args))

    def __eq__(self, x):
        return _AlarmEventWrapper.BaseEvent___eq__(self, x)

    def __ne__(self, x):
        return _AlarmEventWrapper.BaseEvent___ne__(self, x)

    def eventId(self, *args):
        return _AlarmEventWrapper.BaseEvent_eventId(self, *args)

    def sourceId(self, *args):
        return _AlarmEventWrapper.BaseEvent_sourceId(self, *args)

    def sourceType(self, *args):
        return _AlarmEventWrapper.BaseEvent_sourceType(self, *args)

    def severity(self, *args):
        return _AlarmEventWrapper.BaseEvent_severity(self, *args)

    def message(self, *args):
        return _AlarmEventWrapper.BaseEvent_message(self, *args)

    def timestamp(self, *args):
        return _AlarmEventWrapper.BaseEvent_timestamp(self, *args)

    def userId(self, *args):
        return _AlarmEventWrapper.BaseEvent_userId(self, *args)

    def deviceId(self, *args):
        return _AlarmEventWrapper.BaseEvent_deviceId(self, *args)

# Register BaseEvent in _AlarmEventWrapper:
_AlarmEventWrapper.BaseEvent_swigregister(BaseEvent)

FASTDDS_GEN_API_VER = _AlarmEventWrapper.FASTDDS_GEN_API_VER
class BaseEventPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _AlarmEventWrapper.BaseEventPubSubType_swiginit(self, _AlarmEventWrapper.new_BaseEventPubSubType())
    __swig_destroy__ = _AlarmEventWrapper.delete_BaseEventPubSubType

    def serialize(self, data, payload, data_representation):
        return _AlarmEventWrapper.BaseEventPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _AlarmEventWrapper.BaseEventPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _AlarmEventWrapper.BaseEventPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _AlarmEventWrapper.BaseEventPubSubType_compute_key(self, *args)

    def create_data(self):
        return _AlarmEventWrapper.BaseEventPubSubType_create_data(self)

    def delete_data(self, data):
        return _AlarmEventWrapper.BaseEventPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _AlarmEventWrapper.BaseEventPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _AlarmEventWrapper.BaseEventPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _AlarmEventWrapper.BaseEventPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _AlarmEventWrapper.BaseEventPubSubType_construct_sample(self, memory)

# Register BaseEventPubSubType in _AlarmEventWrapper:
_AlarmEventWrapper.BaseEventPubSubType_swigregister(BaseEventPubSubType)

class _BoundingBoxSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete__BoundingBoxSeq

# Register _BoundingBoxSeq in _AlarmEventWrapper:
_AlarmEventWrapper._BoundingBoxSeq_swigregister(_BoundingBoxSeq)

class BoundingBoxSeq(_BoundingBoxSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_BoundingBoxSeq

    def __init__(self, *args):
        _AlarmEventWrapper.BoundingBoxSeq_swiginit(self, _AlarmEventWrapper.new_BoundingBoxSeq(*args))

    def __len__(self):
        return _AlarmEventWrapper.BoundingBoxSeq___len__(self)

    def __getitem__(self, i):
        return _AlarmEventWrapper.BoundingBoxSeq___getitem__(self, i)

# Register BoundingBoxSeq in _AlarmEventWrapper:
_AlarmEventWrapper.BoundingBoxSeq_swigregister(BoundingBoxSeq)

class _TrackDataSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete__TrackDataSeq

# Register _TrackDataSeq in _AlarmEventWrapper:
_AlarmEventWrapper._TrackDataSeq_swigregister(_TrackDataSeq)

class TrackDataSeq(_TrackDataSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_TrackDataSeq

    def __init__(self, *args):
        _AlarmEventWrapper.TrackDataSeq_swiginit(self, _AlarmEventWrapper.new_TrackDataSeq(*args))

    def __len__(self):
        return _AlarmEventWrapper.TrackDataSeq___len__(self)

    def __getitem__(self, i):
        return _AlarmEventWrapper.TrackDataSeq___getitem__(self, i)

# Register TrackDataSeq in _AlarmEventWrapper:
_AlarmEventWrapper.TrackDataSeq_swigregister(TrackDataSeq)

class _GeoPositionSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete__GeoPositionSeq

# Register _GeoPositionSeq in _AlarmEventWrapper:
_AlarmEventWrapper._GeoPositionSeq_swigregister(_GeoPositionSeq)

class GeoPositionSeq(_GeoPositionSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_GeoPositionSeq

    def __init__(self, *args):
        _AlarmEventWrapper.GeoPositionSeq_swiginit(self, _AlarmEventWrapper.new_GeoPositionSeq(*args))

    def __len__(self):
        return _AlarmEventWrapper.GeoPositionSeq___len__(self)

    def __getitem__(self, i):
        return _AlarmEventWrapper.GeoPositionSeq___getitem__(self, i)

# Register GeoPositionSeq in _AlarmEventWrapper:
_AlarmEventWrapper.GeoPositionSeq_swigregister(GeoPositionSeq)

class AlarmType_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _AlarmEventWrapper.AlarmType_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _AlarmEventWrapper.AlarmType_vector___nonzero__(self)

    def __bool__(self):
        return _AlarmEventWrapper.AlarmType_vector___bool__(self)

    def __len__(self):
        return _AlarmEventWrapper.AlarmType_vector___len__(self)

    def __getslice__(self, i, j):
        return _AlarmEventWrapper.AlarmType_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _AlarmEventWrapper.AlarmType_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _AlarmEventWrapper.AlarmType_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _AlarmEventWrapper.AlarmType_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _AlarmEventWrapper.AlarmType_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _AlarmEventWrapper.AlarmType_vector___setitem__(self, *args)

    def pop(self):
        return _AlarmEventWrapper.AlarmType_vector_pop(self)

    def append(self, x):
        return _AlarmEventWrapper.AlarmType_vector_append(self, x)

    def empty(self):
        return _AlarmEventWrapper.AlarmType_vector_empty(self)

    def size(self):
        return _AlarmEventWrapper.AlarmType_vector_size(self)

    def swap(self, v):
        return _AlarmEventWrapper.AlarmType_vector_swap(self, v)

    def begin(self):
        return _AlarmEventWrapper.AlarmType_vector_begin(self)

    def end(self):
        return _AlarmEventWrapper.AlarmType_vector_end(self)

    def rbegin(self):
        return _AlarmEventWrapper.AlarmType_vector_rbegin(self)

    def rend(self):
        return _AlarmEventWrapper.AlarmType_vector_rend(self)

    def clear(self):
        return _AlarmEventWrapper.AlarmType_vector_clear(self)

    def get_allocator(self):
        return _AlarmEventWrapper.AlarmType_vector_get_allocator(self)

    def pop_back(self):
        return _AlarmEventWrapper.AlarmType_vector_pop_back(self)

    def erase(self, *args):
        return _AlarmEventWrapper.AlarmType_vector_erase(self, *args)

    def __init__(self, *args):
        _AlarmEventWrapper.AlarmType_vector_swiginit(self, _AlarmEventWrapper.new_AlarmType_vector(*args))

    def push_back(self, x):
        return _AlarmEventWrapper.AlarmType_vector_push_back(self, x)

    def front(self):
        return _AlarmEventWrapper.AlarmType_vector_front(self)

    def back(self):
        return _AlarmEventWrapper.AlarmType_vector_back(self)

    def assign(self, n, x):
        return _AlarmEventWrapper.AlarmType_vector_assign(self, n, x)

    def resize(self, *args):
        return _AlarmEventWrapper.AlarmType_vector_resize(self, *args)

    def insert(self, *args):
        return _AlarmEventWrapper.AlarmType_vector_insert(self, *args)

    def reserve(self, n):
        return _AlarmEventWrapper.AlarmType_vector_reserve(self, n)

    def capacity(self):
        return _AlarmEventWrapper.AlarmType_vector_capacity(self)
    __swig_destroy__ = _AlarmEventWrapper.delete_AlarmType_vector

# Register AlarmType_vector in _AlarmEventWrapper:
_AlarmEventWrapper.AlarmType_vector_swigregister(AlarmType_vector)

class _AlarmInfoSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete__AlarmInfoSeq

# Register _AlarmInfoSeq in _AlarmEventWrapper:
_AlarmEventWrapper._AlarmInfoSeq_swigregister(_AlarmInfoSeq)

class AlarmInfoSeq(_AlarmInfoSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_AlarmInfoSeq

    def __init__(self, *args):
        _AlarmEventWrapper.AlarmInfoSeq_swiginit(self, _AlarmEventWrapper.new_AlarmInfoSeq(*args))

    def __len__(self):
        return _AlarmEventWrapper.AlarmInfoSeq___len__(self)

    def __getitem__(self, i):
        return _AlarmEventWrapper.AlarmInfoSeq___getitem__(self, i)

# Register AlarmInfoSeq in _AlarmEventWrapper:
_AlarmEventWrapper.AlarmInfoSeq_swigregister(AlarmInfoSeq)

class AlarmInfo_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _AlarmEventWrapper.AlarmInfo_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _AlarmEventWrapper.AlarmInfo_vector___nonzero__(self)

    def __bool__(self):
        return _AlarmEventWrapper.AlarmInfo_vector___bool__(self)

    def __len__(self):
        return _AlarmEventWrapper.AlarmInfo_vector___len__(self)

    def __getslice__(self, i, j):
        return _AlarmEventWrapper.AlarmInfo_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _AlarmEventWrapper.AlarmInfo_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _AlarmEventWrapper.AlarmInfo_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _AlarmEventWrapper.AlarmInfo_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _AlarmEventWrapper.AlarmInfo_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _AlarmEventWrapper.AlarmInfo_vector___setitem__(self, *args)

    def pop(self):
        return _AlarmEventWrapper.AlarmInfo_vector_pop(self)

    def append(self, x):
        return _AlarmEventWrapper.AlarmInfo_vector_append(self, x)

    def empty(self):
        return _AlarmEventWrapper.AlarmInfo_vector_empty(self)

    def size(self):
        return _AlarmEventWrapper.AlarmInfo_vector_size(self)

    def swap(self, v):
        return _AlarmEventWrapper.AlarmInfo_vector_swap(self, v)

    def begin(self):
        return _AlarmEventWrapper.AlarmInfo_vector_begin(self)

    def end(self):
        return _AlarmEventWrapper.AlarmInfo_vector_end(self)

    def rbegin(self):
        return _AlarmEventWrapper.AlarmInfo_vector_rbegin(self)

    def rend(self):
        return _AlarmEventWrapper.AlarmInfo_vector_rend(self)

    def clear(self):
        return _AlarmEventWrapper.AlarmInfo_vector_clear(self)

    def get_allocator(self):
        return _AlarmEventWrapper.AlarmInfo_vector_get_allocator(self)

    def pop_back(self):
        return _AlarmEventWrapper.AlarmInfo_vector_pop_back(self)

    def erase(self, *args):
        return _AlarmEventWrapper.AlarmInfo_vector_erase(self, *args)

    def __init__(self, *args):
        _AlarmEventWrapper.AlarmInfo_vector_swiginit(self, _AlarmEventWrapper.new_AlarmInfo_vector(*args))

    def push_back(self, x):
        return _AlarmEventWrapper.AlarmInfo_vector_push_back(self, x)

    def front(self):
        return _AlarmEventWrapper.AlarmInfo_vector_front(self)

    def back(self):
        return _AlarmEventWrapper.AlarmInfo_vector_back(self)

    def assign(self, n, x):
        return _AlarmEventWrapper.AlarmInfo_vector_assign(self, n, x)

    def resize(self, *args):
        return _AlarmEventWrapper.AlarmInfo_vector_resize(self, *args)

    def insert(self, *args):
        return _AlarmEventWrapper.AlarmInfo_vector_insert(self, *args)

    def reserve(self, n):
        return _AlarmEventWrapper.AlarmInfo_vector_reserve(self, n)

    def capacity(self):
        return _AlarmEventWrapper.AlarmInfo_vector_capacity(self)
    __swig_destroy__ = _AlarmEventWrapper.delete_AlarmInfo_vector

# Register AlarmInfo_vector in _AlarmEventWrapper:
_AlarmEventWrapper.AlarmInfo_vector_swigregister(AlarmInfo_vector)

class _AlarmEventSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete__AlarmEventSeq

# Register _AlarmEventSeq in _AlarmEventWrapper:
_AlarmEventWrapper._AlarmEventSeq_swigregister(_AlarmEventSeq)

class AlarmEventSeq(_AlarmEventSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_AlarmEventSeq

    def __init__(self, *args):
        _AlarmEventWrapper.AlarmEventSeq_swiginit(self, _AlarmEventWrapper.new_AlarmEventSeq(*args))

    def __len__(self):
        return _AlarmEventWrapper.AlarmEventSeq___len__(self)

    def __getitem__(self, i):
        return _AlarmEventWrapper.AlarmEventSeq___getitem__(self, i)

# Register AlarmEventSeq in _AlarmEventWrapper:
_AlarmEventWrapper.AlarmEventSeq_swigregister(AlarmEventSeq)

AlarmType_TRACK_AREA = _AlarmEventWrapper.AlarmType_TRACK_AREA
AlarmType_TARGET_BEHAVIOR = _AlarmEventWrapper.AlarmType_TARGET_BEHAVIOR
AlarmType_TARGET_ATTR = _AlarmEventWrapper.AlarmType_TARGET_ATTR
AlarmType_DEVICE = _AlarmEventWrapper.AlarmType_DEVICE
AlarmType_CUSTOM_TYPE = _AlarmEventWrapper.AlarmType_CUSTOM_TYPE
TrackType_FUSE = _AlarmEventWrapper.TrackType_FUSE
TrackType_BIRD = _AlarmEventWrapper.TrackType_BIRD
AlarmStatus_ACTIVE = _AlarmEventWrapper.AlarmStatus_ACTIVE
AlarmStatus_CANCELED = _AlarmEventWrapper.AlarmStatus_CANCELED
AlarmStatus_DELETED = _AlarmEventWrapper.AlarmStatus_DELETED
AlarmStatus_FOCUS = _AlarmEventWrapper.AlarmStatus_FOCUS
AlarmStatus_AUTO_RESOLVED = _AlarmEventWrapper.AlarmStatus_AUTO_RESOLVED
AlarmTaskStatus_UNASSIGNED = _AlarmEventWrapper.AlarmTaskStatus_UNASSIGNED
AlarmTaskStatus_ASSIGNED = _AlarmEventWrapper.AlarmTaskStatus_ASSIGNED
AlarmTaskStatus_VERIFY_FAILED = _AlarmEventWrapper.AlarmTaskStatus_VERIFY_FAILED
AlarmTaskStatus_VERIFY_SUCCESS = _AlarmEventWrapper.AlarmTaskStatus_VERIFY_SUCCESS
class BoundingBox(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_BoundingBox

    def __init__(self, *args):
        _AlarmEventWrapper.BoundingBox_swiginit(self, _AlarmEventWrapper.new_BoundingBox(*args))

    def __eq__(self, x):
        return _AlarmEventWrapper.BoundingBox___eq__(self, x)

    def __ne__(self, x):
        return _AlarmEventWrapper.BoundingBox___ne__(self, x)

    def cameraId(self, *args):
        return _AlarmEventWrapper.BoundingBox_cameraId(self, *args)

    def syncHeader(self, *args):
        return _AlarmEventWrapper.BoundingBox_syncHeader(self, *args)

    def x(self, *args):
        return _AlarmEventWrapper.BoundingBox_x(self, *args)

    def y(self, *args):
        return _AlarmEventWrapper.BoundingBox_y(self, *args)

    def width(self, *args):
        return _AlarmEventWrapper.BoundingBox_width(self, *args)

    def height(self, *args):
        return _AlarmEventWrapper.BoundingBox_height(self, *args)

    def boxId(self, *args):
        return _AlarmEventWrapper.BoundingBox_boxId(self, *args)

    def trackId(self, *args):
        return _AlarmEventWrapper.BoundingBox_trackId(self, *args)

    def classId(self, *args):
        return _AlarmEventWrapper.BoundingBox_classId(self, *args)

    def behaviorId(self, *args):
        return _AlarmEventWrapper.BoundingBox_behaviorId(self, *args)

# Register BoundingBox in _AlarmEventWrapper:
_AlarmEventWrapper.BoundingBox_swigregister(BoundingBox)

class TrackData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_TrackData

    def __init__(self, *args):
        _AlarmEventWrapper.TrackData_swiginit(self, _AlarmEventWrapper.new_TrackData(*args))

    def __eq__(self, x):
        return _AlarmEventWrapper.TrackData___eq__(self, x)

    def __ne__(self, x):
        return _AlarmEventWrapper.TrackData___ne__(self, x)

    def trackId(self, *args):
        return _AlarmEventWrapper.TrackData_trackId(self, *args)

    def mmsi(self, *args):
        return _AlarmEventWrapper.TrackData_mmsi(self, *args)

    def longitude(self, *args):
        return _AlarmEventWrapper.TrackData_longitude(self, *args)

    def latitude(self, *args):
        return _AlarmEventWrapper.TrackData_latitude(self, *args)

    def course(self, *args):
        return _AlarmEventWrapper.TrackData_course(self, *args)

    def speed(self, *args):
        return _AlarmEventWrapper.TrackData_speed(self, *args)

    def height(self, *args):
        return _AlarmEventWrapper.TrackData_height(self, *args)

    def timeStamp(self, *args):
        return _AlarmEventWrapper.TrackData_timeStamp(self, *args)

    def trackType(self, *args):
        return _AlarmEventWrapper.TrackData_trackType(self, *args)

# Register TrackData in _AlarmEventWrapper:
_AlarmEventWrapper.TrackData_swigregister(TrackData)

class GeoPosition(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_GeoPosition

    def __init__(self, *args):
        _AlarmEventWrapper.GeoPosition_swiginit(self, _AlarmEventWrapper.new_GeoPosition(*args))

    def __eq__(self, x):
        return _AlarmEventWrapper.GeoPosition___eq__(self, x)

    def __ne__(self, x):
        return _AlarmEventWrapper.GeoPosition___ne__(self, x)

    def longitude(self, *args):
        return _AlarmEventWrapper.GeoPosition_longitude(self, *args)

    def latitude(self, *args):
        return _AlarmEventWrapper.GeoPosition_latitude(self, *args)

    def altitude(self, *args):
        return _AlarmEventWrapper.GeoPosition_altitude(self, *args)

# Register GeoPosition in _AlarmEventWrapper:
_AlarmEventWrapper.GeoPosition_swigregister(GeoPosition)

class AlarmInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_AlarmInfo

    def __init__(self, *args):
        _AlarmEventWrapper.AlarmInfo_swiginit(self, _AlarmEventWrapper.new_AlarmInfo(*args))

    def __eq__(self, x):
        return _AlarmEventWrapper.AlarmInfo___eq__(self, x)

    def __ne__(self, x):
        return _AlarmEventWrapper.AlarmInfo___ne__(self, x)

    def alarmId(self, *args):
        return _AlarmEventWrapper.AlarmInfo_alarmId(self, *args)

    def alarmType(self, *args):
        return _AlarmEventWrapper.AlarmInfo_alarmType(self, *args)

    def status(self, *args):
        return _AlarmEventWrapper.AlarmInfo_status(self, *args)

    def taskStatus(self, *args):
        return _AlarmEventWrapper.AlarmInfo_taskStatus(self, *args)

    def alarmContent(self, *args):
        return _AlarmEventWrapper.AlarmInfo_alarmContent(self, *args)

    def alarmLevel(self, *args):
        return _AlarmEventWrapper.AlarmInfo_alarmLevel(self, *args)

    def areaId(self, *args):
        return _AlarmEventWrapper.AlarmInfo_areaId(self, *args)

    def areaName(self, *args):
        return _AlarmEventWrapper.AlarmInfo_areaName(self, *args)

    def trackId(self, *args):
        return _AlarmEventWrapper.AlarmInfo_trackId(self, *args)

    def classId(self, *args):
        return _AlarmEventWrapper.AlarmInfo_classId(self, *args)

    def behaviorId(self, *args):
        return _AlarmEventWrapper.AlarmInfo_behaviorId(self, *args)

    def position(self, *args):
        return _AlarmEventWrapper.AlarmInfo_position(self, *args)

    def updateTime(self, *args):
        return _AlarmEventWrapper.AlarmInfo_updateTime(self, *args)

    def resolvedTime(self, *args):
        return _AlarmEventWrapper.AlarmInfo_resolvedTime(self, *args)

    def resolvedBy(self, *args):
        return _AlarmEventWrapper.AlarmInfo_resolvedBy(self, *args)

    def resolutionDetails(self, *args):
        return _AlarmEventWrapper.AlarmInfo_resolutionDetails(self, *args)

    def alarmRuleId(self, *args):
        return _AlarmEventWrapper.AlarmInfo_alarmRuleId(self, *args)

    def targetBox(self, *args):
        return _AlarmEventWrapper.AlarmInfo_targetBox(self, *args)

    def track(self, *args):
        return _AlarmEventWrapper.AlarmInfo_track(self, *args)

# Register AlarmInfo in _AlarmEventWrapper:
_AlarmEventWrapper.AlarmInfo_swigregister(AlarmInfo)

class AlarmEvent(BaseEvent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlarmEventWrapper.delete_AlarmEvent

    def __init__(self, *args):
        _AlarmEventWrapper.AlarmEvent_swiginit(self, _AlarmEventWrapper.new_AlarmEvent(*args))

    def __eq__(self, x):
        return _AlarmEventWrapper.AlarmEvent___eq__(self, x)

    def __ne__(self, x):
        return _AlarmEventWrapper.AlarmEvent___ne__(self, x)

    def alarm(self, *args):
        return _AlarmEventWrapper.AlarmEvent_alarm(self, *args)

# Register AlarmEvent in _AlarmEventWrapper:
_AlarmEventWrapper.AlarmEvent_swigregister(AlarmEvent)

class BoundingBoxPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _AlarmEventWrapper.BoundingBoxPubSubType_swiginit(self, _AlarmEventWrapper.new_BoundingBoxPubSubType())
    __swig_destroy__ = _AlarmEventWrapper.delete_BoundingBoxPubSubType

    def serialize(self, data, payload, data_representation):
        return _AlarmEventWrapper.BoundingBoxPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _AlarmEventWrapper.BoundingBoxPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _AlarmEventWrapper.BoundingBoxPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _AlarmEventWrapper.BoundingBoxPubSubType_compute_key(self, *args)

    def create_data(self):
        return _AlarmEventWrapper.BoundingBoxPubSubType_create_data(self)

    def delete_data(self, data):
        return _AlarmEventWrapper.BoundingBoxPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _AlarmEventWrapper.BoundingBoxPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _AlarmEventWrapper.BoundingBoxPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _AlarmEventWrapper.BoundingBoxPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _AlarmEventWrapper.BoundingBoxPubSubType_construct_sample(self, memory)

# Register BoundingBoxPubSubType in _AlarmEventWrapper:
_AlarmEventWrapper.BoundingBoxPubSubType_swigregister(BoundingBoxPubSubType)

class TrackDataPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _AlarmEventWrapper.TrackDataPubSubType_swiginit(self, _AlarmEventWrapper.new_TrackDataPubSubType())
    __swig_destroy__ = _AlarmEventWrapper.delete_TrackDataPubSubType

    def serialize(self, data, payload, data_representation):
        return _AlarmEventWrapper.TrackDataPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _AlarmEventWrapper.TrackDataPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _AlarmEventWrapper.TrackDataPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _AlarmEventWrapper.TrackDataPubSubType_compute_key(self, *args)

    def create_data(self):
        return _AlarmEventWrapper.TrackDataPubSubType_create_data(self)

    def delete_data(self, data):
        return _AlarmEventWrapper.TrackDataPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _AlarmEventWrapper.TrackDataPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _AlarmEventWrapper.TrackDataPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _AlarmEventWrapper.TrackDataPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _AlarmEventWrapper.TrackDataPubSubType_construct_sample(self, memory)

# Register TrackDataPubSubType in _AlarmEventWrapper:
_AlarmEventWrapper.TrackDataPubSubType_swigregister(TrackDataPubSubType)

class GeoPositionPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _AlarmEventWrapper.GeoPositionPubSubType_swiginit(self, _AlarmEventWrapper.new_GeoPositionPubSubType())
    __swig_destroy__ = _AlarmEventWrapper.delete_GeoPositionPubSubType

    def serialize(self, data, payload, data_representation):
        return _AlarmEventWrapper.GeoPositionPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _AlarmEventWrapper.GeoPositionPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _AlarmEventWrapper.GeoPositionPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _AlarmEventWrapper.GeoPositionPubSubType_compute_key(self, *args)

    def create_data(self):
        return _AlarmEventWrapper.GeoPositionPubSubType_create_data(self)

    def delete_data(self, data):
        return _AlarmEventWrapper.GeoPositionPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _AlarmEventWrapper.GeoPositionPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _AlarmEventWrapper.GeoPositionPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _AlarmEventWrapper.GeoPositionPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _AlarmEventWrapper.GeoPositionPubSubType_construct_sample(self, memory)

# Register GeoPositionPubSubType in _AlarmEventWrapper:
_AlarmEventWrapper.GeoPositionPubSubType_swigregister(GeoPositionPubSubType)

class AlarmInfoPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _AlarmEventWrapper.AlarmInfoPubSubType_swiginit(self, _AlarmEventWrapper.new_AlarmInfoPubSubType())
    __swig_destroy__ = _AlarmEventWrapper.delete_AlarmInfoPubSubType

    def serialize(self, data, payload, data_representation):
        return _AlarmEventWrapper.AlarmInfoPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _AlarmEventWrapper.AlarmInfoPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _AlarmEventWrapper.AlarmInfoPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _AlarmEventWrapper.AlarmInfoPubSubType_compute_key(self, *args)

    def create_data(self):
        return _AlarmEventWrapper.AlarmInfoPubSubType_create_data(self)

    def delete_data(self, data):
        return _AlarmEventWrapper.AlarmInfoPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _AlarmEventWrapper.AlarmInfoPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _AlarmEventWrapper.AlarmInfoPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _AlarmEventWrapper.AlarmInfoPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _AlarmEventWrapper.AlarmInfoPubSubType_construct_sample(self, memory)

# Register AlarmInfoPubSubType in _AlarmEventWrapper:
_AlarmEventWrapper.AlarmInfoPubSubType_swigregister(AlarmInfoPubSubType)

class AlarmEventPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _AlarmEventWrapper.AlarmEventPubSubType_swiginit(self, _AlarmEventWrapper.new_AlarmEventPubSubType())
    __swig_destroy__ = _AlarmEventWrapper.delete_AlarmEventPubSubType

    def serialize(self, data, payload, data_representation):
        return _AlarmEventWrapper.AlarmEventPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _AlarmEventWrapper.AlarmEventPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _AlarmEventWrapper.AlarmEventPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _AlarmEventWrapper.AlarmEventPubSubType_compute_key(self, *args)

    def create_data(self):
        return _AlarmEventWrapper.AlarmEventPubSubType_create_data(self)

    def delete_data(self, data):
        return _AlarmEventWrapper.AlarmEventPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _AlarmEventWrapper.AlarmEventPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _AlarmEventWrapper.AlarmEventPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _AlarmEventWrapper.AlarmEventPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _AlarmEventWrapper.AlarmEventPubSubType_construct_sample(self, memory)

# Register AlarmEventPubSubType in _AlarmEventWrapper:
_AlarmEventWrapper.AlarmEventPubSubType_swigregister(AlarmEventPubSubType)



