// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BaseDeviceStatusTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "BaseDeviceStatusTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "BaseDeviceStatus.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace casia {
namespace device {
namespace status {
void register_ExecutionState_type_identifier(
        TypeIdentifierPair& type_ids_ExecutionState)
{
    ReturnCode_t return_code_ExecutionState {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ExecutionState =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "casia::device::status::ExecutionState", type_ids_ExecutionState);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ExecutionState)
    {
        EnumTypeFlag enum_flags_ExecutionState = 0;
        BitBound bit_bound_ExecutionState = 32;
        CommonEnumeratedHeader common_ExecutionState = TypeObjectUtils::build_common_enumerated_header(bit_bound_ExecutionState);
        QualifiedTypeName type_name_ExecutionState = "casia::device::status::ExecutionState";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ExecutionState;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ExecutionState;
        CompleteTypeDetail detail_ExecutionState = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ExecutionState, ann_custom_ExecutionState, type_name_ExecutionState.to_string());
        CompleteEnumeratedHeader header_ExecutionState = TypeObjectUtils::build_complete_enumerated_header(common_ExecutionState, detail_ExecutionState);
        CompleteEnumeratedLiteralSeq literal_seq_ExecutionState;
        {
            EnumeratedLiteralFlag flags_EXECUTING = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_EXECUTING = TypeObjectUtils::build_common_enumerated_literal(0, flags_EXECUTING);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_EXECUTING;
            ann_custom_ExecutionState.reset();
            MemberName name_EXECUTING = "EXECUTING";
            CompleteMemberDetail detail_EXECUTING = TypeObjectUtils::build_complete_member_detail(name_EXECUTING, member_ann_builtin_EXECUTING, ann_custom_ExecutionState);
            CompleteEnumeratedLiteral literal_EXECUTING = TypeObjectUtils::build_complete_enumerated_literal(common_EXECUTING, detail_EXECUTING);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_ExecutionState, literal_EXECUTING);
        }
        {
            EnumeratedLiteralFlag flags_COMPLETED = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_COMPLETED = TypeObjectUtils::build_common_enumerated_literal(1, flags_COMPLETED);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_COMPLETED;
            ann_custom_ExecutionState.reset();
            MemberName name_COMPLETED = "COMPLETED";
            CompleteMemberDetail detail_COMPLETED = TypeObjectUtils::build_complete_member_detail(name_COMPLETED, member_ann_builtin_COMPLETED, ann_custom_ExecutionState);
            CompleteEnumeratedLiteral literal_COMPLETED = TypeObjectUtils::build_complete_enumerated_literal(common_COMPLETED, detail_COMPLETED);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_ExecutionState, literal_COMPLETED);
        }
        {
            EnumeratedLiteralFlag flags_ALREADY_CLEARED = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_ALREADY_CLEARED = TypeObjectUtils::build_common_enumerated_literal(2, flags_ALREADY_CLEARED);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ALREADY_CLEARED;
            ann_custom_ExecutionState.reset();
            MemberName name_ALREADY_CLEARED = "ALREADY_CLEARED";
            CompleteMemberDetail detail_ALREADY_CLEARED = TypeObjectUtils::build_complete_member_detail(name_ALREADY_CLEARED, member_ann_builtin_ALREADY_CLEARED, ann_custom_ExecutionState);
            CompleteEnumeratedLiteral literal_ALREADY_CLEARED = TypeObjectUtils::build_complete_enumerated_literal(common_ALREADY_CLEARED, detail_ALREADY_CLEARED);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_ExecutionState, literal_ALREADY_CLEARED);
        }
        {
            EnumeratedLiteralFlag flags_SAVED = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_SAVED = TypeObjectUtils::build_common_enumerated_literal(3, flags_SAVED);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_SAVED;
            ann_custom_ExecutionState.reset();
            MemberName name_SAVED = "SAVED";
            CompleteMemberDetail detail_SAVED = TypeObjectUtils::build_complete_member_detail(name_SAVED, member_ann_builtin_SAVED, ann_custom_ExecutionState);
            CompleteEnumeratedLiteral literal_SAVED = TypeObjectUtils::build_complete_enumerated_literal(common_SAVED, detail_SAVED);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_ExecutionState, literal_SAVED);
        }
        {
            EnumeratedLiteralFlag flags_FAILED = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_FAILED = TypeObjectUtils::build_common_enumerated_literal(4, flags_FAILED);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_FAILED;
            ann_custom_ExecutionState.reset();
            MemberName name_FAILED = "FAILED";
            CompleteMemberDetail detail_FAILED = TypeObjectUtils::build_complete_member_detail(name_FAILED, member_ann_builtin_FAILED, ann_custom_ExecutionState);
            CompleteEnumeratedLiteral literal_FAILED = TypeObjectUtils::build_complete_enumerated_literal(common_FAILED, detail_FAILED);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_ExecutionState, literal_FAILED);
        }
        CompleteEnumeratedType enumerated_type_ExecutionState = TypeObjectUtils::build_complete_enumerated_type(enum_flags_ExecutionState, header_ExecutionState,
                literal_seq_ExecutionState);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_enumerated_type_object(enumerated_type_ExecutionState, type_name_ExecutionState.to_string(), type_ids_ExecutionState))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "casia::device::status::ExecutionState already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_GeoPosition_type_identifier(
        TypeIdentifierPair& type_ids_GeoPosition)
{

    ReturnCode_t return_code_GeoPosition {eprosima::fastdds::dds::RETCODE_OK};
    return_code_GeoPosition =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "casia::device::status::GeoPosition", type_ids_GeoPosition);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_GeoPosition)
    {
        StructTypeFlag struct_flags_GeoPosition = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_GeoPosition = "casia::device::status::GeoPosition";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_GeoPosition;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_GeoPosition;
        CompleteTypeDetail detail_GeoPosition = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_GeoPosition, ann_custom_GeoPosition, type_name_GeoPosition.to_string());
        CompleteStructHeader header_GeoPosition;
        header_GeoPosition = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_GeoPosition);
        CompleteStructMemberSeq member_seq_GeoPosition;
        {
            TypeIdentifierPair type_ids_longitude;
            ReturnCode_t return_code_longitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_longitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_longitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_longitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "longitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_longitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_longitude = 0x00000000;
            bool common_longitude_ec {false};
            CommonStructMember common_longitude {TypeObjectUtils::build_common_struct_member(member_id_longitude, member_flags_longitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_longitude, common_longitude_ec))};
            if (!common_longitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure longitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_longitude = "longitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_longitude;
            ann_custom_GeoPosition.reset();
            CompleteMemberDetail detail_longitude = TypeObjectUtils::build_complete_member_detail(name_longitude, member_ann_builtin_longitude, ann_custom_GeoPosition);
            CompleteStructMember member_longitude = TypeObjectUtils::build_complete_struct_member(common_longitude, detail_longitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_GeoPosition, member_longitude);
        }
        {
            TypeIdentifierPair type_ids_latitude;
            ReturnCode_t return_code_latitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_latitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_latitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_latitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "latitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_latitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_latitude = 0x00000001;
            bool common_latitude_ec {false};
            CommonStructMember common_latitude {TypeObjectUtils::build_common_struct_member(member_id_latitude, member_flags_latitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_latitude, common_latitude_ec))};
            if (!common_latitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure latitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_latitude = "latitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_latitude;
            ann_custom_GeoPosition.reset();
            CompleteMemberDetail detail_latitude = TypeObjectUtils::build_complete_member_detail(name_latitude, member_ann_builtin_latitude, ann_custom_GeoPosition);
            CompleteStructMember member_latitude = TypeObjectUtils::build_complete_struct_member(common_latitude, detail_latitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_GeoPosition, member_latitude);
        }
        {
            TypeIdentifierPair type_ids_altitude;
            ReturnCode_t return_code_altitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_altitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_altitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_altitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "altitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_altitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_altitude = 0x00000002;
            bool common_altitude_ec {false};
            CommonStructMember common_altitude {TypeObjectUtils::build_common_struct_member(member_id_altitude, member_flags_altitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_altitude, common_altitude_ec))};
            if (!common_altitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure altitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_altitude = "altitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_altitude;
            ann_custom_GeoPosition.reset();
            CompleteMemberDetail detail_altitude = TypeObjectUtils::build_complete_member_detail(name_altitude, member_ann_builtin_altitude, ann_custom_GeoPosition);
            CompleteStructMember member_altitude = TypeObjectUtils::build_complete_struct_member(common_altitude, detail_altitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_GeoPosition, member_altitude);
        }
        CompleteStructType struct_type_GeoPosition = TypeObjectUtils::build_complete_struct_type(struct_flags_GeoPosition, header_GeoPosition, member_seq_GeoPosition);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_GeoPosition, type_name_GeoPosition.to_string(), type_ids_GeoPosition))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "casia::device::status::GeoPosition already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_BaseDeviceStatus_type_identifier(
        TypeIdentifierPair& type_ids_BaseDeviceStatus)
{

    ReturnCode_t return_code_BaseDeviceStatus {eprosima::fastdds::dds::RETCODE_OK};
    return_code_BaseDeviceStatus =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "casia::device::status::BaseDeviceStatus", type_ids_BaseDeviceStatus);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_BaseDeviceStatus)
    {
        StructTypeFlag struct_flags_BaseDeviceStatus = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_BaseDeviceStatus = "casia::device::status::BaseDeviceStatus";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_BaseDeviceStatus;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_BaseDeviceStatus;
        CompleteTypeDetail detail_BaseDeviceStatus = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_BaseDeviceStatus, ann_custom_BaseDeviceStatus, type_name_BaseDeviceStatus.to_string());
        CompleteStructHeader header_BaseDeviceStatus;
        header_BaseDeviceStatus = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_BaseDeviceStatus);
        CompleteStructMemberSeq member_seq_BaseDeviceStatus;
        {
            TypeIdentifierPair type_ids_entityId;
            ReturnCode_t return_code_entityId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_entityId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_entityId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_entityId)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_entityId))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_entityId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_entityId = 0x00000000;
            bool common_entityId_ec {false};
            CommonStructMember common_entityId {TypeObjectUtils::build_common_struct_member(member_id_entityId, member_flags_entityId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_entityId, common_entityId_ec))};
            if (!common_entityId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure entityId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_entityId = "entityId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_entityId;
            ann_custom_BaseDeviceStatus.reset();
            CompleteMemberDetail detail_entityId = TypeObjectUtils::build_complete_member_detail(name_entityId, member_ann_builtin_entityId, ann_custom_BaseDeviceStatus);
            CompleteStructMember member_entityId = TypeObjectUtils::build_complete_struct_member(common_entityId, detail_entityId);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseDeviceStatus, member_entityId);
        }
        {
            TypeIdentifierPair type_ids_taskType;
            ReturnCode_t return_code_taskType {eprosima::fastdds::dds::RETCODE_OK};
            return_code_taskType =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_taskType);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_taskType)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_taskType))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_taskType = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_taskType = 0x00000001;
            bool common_taskType_ec {false};
            CommonStructMember common_taskType {TypeObjectUtils::build_common_struct_member(member_id_taskType, member_flags_taskType, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_taskType, common_taskType_ec))};
            if (!common_taskType_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure taskType member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_taskType = "taskType";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_taskType;
            ann_custom_BaseDeviceStatus.reset();
            CompleteMemberDetail detail_taskType = TypeObjectUtils::build_complete_member_detail(name_taskType, member_ann_builtin_taskType, ann_custom_BaseDeviceStatus);
            CompleteStructMember member_taskType = TypeObjectUtils::build_complete_struct_member(common_taskType, detail_taskType);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseDeviceStatus, member_taskType);
        }
        {
            TypeIdentifierPair type_ids_executionState;
            ReturnCode_t return_code_executionState {eprosima::fastdds::dds::RETCODE_OK};
            return_code_executionState =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "casia::device::status::ExecutionState", type_ids_executionState);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_executionState)
            {
                casia::device::status::register_ExecutionState_type_identifier(type_ids_executionState);
            }
            StructMemberFlag member_flags_executionState = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_executionState = 0x00000002;
            bool common_executionState_ec {false};
            CommonStructMember common_executionState {TypeObjectUtils::build_common_struct_member(member_id_executionState, member_flags_executionState, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_executionState, common_executionState_ec))};
            if (!common_executionState_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure executionState member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_executionState = "executionState";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_executionState;
            ann_custom_BaseDeviceStatus.reset();
            CompleteMemberDetail detail_executionState = TypeObjectUtils::build_complete_member_detail(name_executionState, member_ann_builtin_executionState, ann_custom_BaseDeviceStatus);
            CompleteStructMember member_executionState = TypeObjectUtils::build_complete_struct_member(common_executionState, detail_executionState);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseDeviceStatus, member_executionState);
        }
        {
            TypeIdentifierPair type_ids_executionTimeMs;
            ReturnCode_t return_code_executionTimeMs {eprosima::fastdds::dds::RETCODE_OK};
            return_code_executionTimeMs =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_executionTimeMs);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_executionTimeMs)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "executionTimeMs Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_executionTimeMs = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_executionTimeMs = 0x00000003;
            bool common_executionTimeMs_ec {false};
            CommonStructMember common_executionTimeMs {TypeObjectUtils::build_common_struct_member(member_id_executionTimeMs, member_flags_executionTimeMs, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_executionTimeMs, common_executionTimeMs_ec))};
            if (!common_executionTimeMs_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure executionTimeMs member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_executionTimeMs = "executionTimeMs";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_executionTimeMs;
            ann_custom_BaseDeviceStatus.reset();
            CompleteMemberDetail detail_executionTimeMs = TypeObjectUtils::build_complete_member_detail(name_executionTimeMs, member_ann_builtin_executionTimeMs, ann_custom_BaseDeviceStatus);
            CompleteStructMember member_executionTimeMs = TypeObjectUtils::build_complete_struct_member(common_executionTimeMs, detail_executionTimeMs);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseDeviceStatus, member_executionTimeMs);
        }
        {
            TypeIdentifierPair type_ids_online;
            ReturnCode_t return_code_online {eprosima::fastdds::dds::RETCODE_OK};
            return_code_online =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_online);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_online)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "online Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_online = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_online = 0x00000004;
            bool common_online_ec {false};
            CommonStructMember common_online {TypeObjectUtils::build_common_struct_member(member_id_online, member_flags_online, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_online, common_online_ec))};
            if (!common_online_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure online member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_online = "online";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_online;
            ann_custom_BaseDeviceStatus.reset();
            CompleteMemberDetail detail_online = TypeObjectUtils::build_complete_member_detail(name_online, member_ann_builtin_online, ann_custom_BaseDeviceStatus);
            CompleteStructMember member_online = TypeObjectUtils::build_complete_struct_member(common_online, detail_online);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseDeviceStatus, member_online);
        }
        {
            TypeIdentifierPair type_ids_position;
            ReturnCode_t return_code_position {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "casia::device::status::GeoPosition", type_ids_position);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position)
            {
                casia::device::status::register_GeoPosition_type_identifier(type_ids_position);
            }
            StructMemberFlag member_flags_position = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position = 0x00000005;
            bool common_position_ec {false};
            CommonStructMember common_position {TypeObjectUtils::build_common_struct_member(member_id_position, member_flags_position, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position, common_position_ec))};
            if (!common_position_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position = "position";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position;
            ann_custom_BaseDeviceStatus.reset();
            CompleteMemberDetail detail_position = TypeObjectUtils::build_complete_member_detail(name_position, member_ann_builtin_position, ann_custom_BaseDeviceStatus);
            CompleteStructMember member_position = TypeObjectUtils::build_complete_struct_member(common_position, detail_position);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseDeviceStatus, member_position);
        }
        {
            TypeIdentifierPair type_ids_elec;
            ReturnCode_t return_code_elec {eprosima::fastdds::dds::RETCODE_OK};
            return_code_elec =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_elec);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_elec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "elec Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_elec = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_elec = 0x00000006;
            bool common_elec_ec {false};
            CommonStructMember common_elec {TypeObjectUtils::build_common_struct_member(member_id_elec, member_flags_elec, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_elec, common_elec_ec))};
            if (!common_elec_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure elec member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_elec = "elec";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_elec;
            ann_custom_BaseDeviceStatus.reset();
            CompleteMemberDetail detail_elec = TypeObjectUtils::build_complete_member_detail(name_elec, member_ann_builtin_elec, ann_custom_BaseDeviceStatus);
            CompleteStructMember member_elec = TypeObjectUtils::build_complete_struct_member(common_elec, detail_elec);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseDeviceStatus, member_elec);
        }
        {
            TypeIdentifierPair type_ids_timestamp;
            ReturnCode_t return_code_timestamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_timestamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_timestamp))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_timestamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp = 0x00000007;
            bool common_timestamp_ec {false};
            CommonStructMember common_timestamp {TypeObjectUtils::build_common_struct_member(member_id_timestamp, member_flags_timestamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp, common_timestamp_ec))};
            if (!common_timestamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp = "timestamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp;
            ann_custom_BaseDeviceStatus.reset();
            CompleteMemberDetail detail_timestamp = TypeObjectUtils::build_complete_member_detail(name_timestamp, member_ann_builtin_timestamp, ann_custom_BaseDeviceStatus);
            CompleteStructMember member_timestamp = TypeObjectUtils::build_complete_struct_member(common_timestamp, detail_timestamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseDeviceStatus, member_timestamp);
        }
        CompleteStructType struct_type_BaseDeviceStatus = TypeObjectUtils::build_complete_struct_type(struct_flags_BaseDeviceStatus, header_BaseDeviceStatus, member_seq_BaseDeviceStatus);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_BaseDeviceStatus, type_name_BaseDeviceStatus.to_string(), type_ids_BaseDeviceStatus))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "casia::device::status::BaseDeviceStatus already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace status

} // namespace device

} // namespace casia

