// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dock2RealTimeStatusCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_DOCK2STATUS_DOCK2REALTIMESTATUSCDRAUX_HPP
#define FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_DOCK2STATUS_DOCK2REALTIMESTATUSCDRAUX_HPP

#include "dock2RealTimeStatus.hpp"

constexpr uint32_t casia_device_status_dock2Status_WirelessLink_max_cdr_typesize {56UL};
constexpr uint32_t casia_device_status_dock2Status_WirelessLink_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_dock2Status_MaintainStatus_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_dock2Status_MaintainStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_CameraList_max_cdr_typesize {280UL};
constexpr uint32_t casia_device_status_dock2Status_CameraList_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_ESIMInfo_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_dock2Status_ESIMInfo_max_key_cdr_typesize {0UL};




constexpr uint32_t casia_device_status_dock2Status_MediaFileDetail_max_cdr_typesize {8UL};
constexpr uint32_t casia_device_status_dock2Status_MediaFileDetail_max_key_cdr_typesize {0UL};








constexpr uint32_t casia_device_status_dock2Status_AirConditioner_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_dock2Status_AirConditioner_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_dock2Status_SubDevice_max_cdr_typesize {532UL};
constexpr uint32_t casia_device_status_dock2Status_SubDevice_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_AlternateLandPoint_max_cdr_typesize {48UL};
constexpr uint32_t casia_device_status_dock2Status_AlternateLandPoint_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_Battery_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_dock2Status_Battery_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_WirelessLinkTopo_max_cdr_typesize {396UL};
constexpr uint32_t casia_device_status_dock2Status_WirelessLinkTopo_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_MaintainStatusItem_max_cdr_typesize {28UL};
constexpr uint32_t casia_device_status_dock2Status_MaintainStatusItem_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_LiveCapacity_max_cdr_typesize {20UL};
constexpr uint32_t casia_device_status_dock2Status_LiveCapacity_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_NetworkState_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_dock2Status_NetworkState_max_key_cdr_typesize {0UL};



constexpr uint32_t casia_device_status_dock2Status_dock2RealTimeStatus_max_cdr_typesize {2716UL};
constexpr uint32_t casia_device_status_dock2Status_dock2RealTimeStatus_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_DeviceList_max_cdr_typesize {280UL};
constexpr uint32_t casia_device_status_dock2Status_DeviceList_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_DongleInfo_max_cdr_typesize {820UL};
constexpr uint32_t casia_device_status_dock2Status_DongleInfo_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_VideoList_max_cdr_typesize {532UL};
constexpr uint32_t casia_device_status_dock2Status_VideoList_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_LiveStatus_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_dock2Status_LiveStatus_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_LiveStatusItem_max_cdr_typesize {536UL};
constexpr uint32_t casia_device_status_dock2Status_LiveStatusItem_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_StorageCapacity_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_dock2Status_StorageCapacity_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_RTCMInfo_max_cdr_typesize {792UL};
constexpr uint32_t casia_device_status_dock2Status_RTCMInfo_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_LeafNode_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_dock2Status_LeafNode_max_key_cdr_typesize {0UL};




constexpr uint32_t casia_device_status_dock2Status_PositionState_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_dock2Status_PositionState_max_key_cdr_typesize {0UL};


constexpr uint32_t casia_device_status_dock2Status_DroneChargeState_max_cdr_typesize {12UL};
constexpr uint32_t casia_device_status_dock2Status_DroneChargeState_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_SIMInfo_max_cdr_typesize {272UL};
constexpr uint32_t casia_device_status_dock2Status_SIMInfo_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_DroneBatteryMaintenanceInfo_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_dock2Status_DroneBatteryMaintenanceInfo_max_key_cdr_typesize {0UL};

constexpr uint32_t casia_device_status_dock2Status_BackupBattery_max_cdr_typesize {24UL};
constexpr uint32_t casia_device_status_dock2Status_BackupBattery_max_key_cdr_typesize {0UL};





constexpr uint32_t casia_device_status_dock2Status_CenterNode_max_cdr_typesize {268UL};
constexpr uint32_t casia_device_status_dock2Status_CenterNode_max_key_cdr_typesize {0UL};




namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::RTCMInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::CenterNode& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::LeafNode& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::WirelessLinkTopo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::AirConditioner& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::ESIMInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::SIMInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::DongleInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::Battery& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::DroneBatteryMaintenanceInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::MaintainStatusItem& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::MaintainStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::PositionState& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::DroneChargeState& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::BackupBattery& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::AlternateLandPoint& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::StorageCapacity& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::VideoList& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::CameraList& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::DeviceList& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::LiveCapacity& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::LiveStatusItem& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::LiveStatus& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::WirelessLink& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::MediaFileDetail& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::NetworkState& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::SubDevice& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const casia::device::status::dock2Status::dock2RealTimeStatus& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__CASIA_DEVICE_STATUS_DOCK2STATUS_DOCK2REALTIMESTATUSCDRAUX_HPP

